// Code generated by goplus from charset.gp. DO NOT EDIT.
//goplus:v v0.28.0

package charset

import (
	"bytes"
	"compress/gzip"
	"io"
	"strings"
	"unicode/utf16"

	"golang.org/x/text/encoding/htmlindex"
)

// Package charset detects and decodes character encodings from raw bytes: it
// sniffs a leading byte-order mark, cleans and folds encoding-label names,
// extracts a charset from a Content-Type-style header, transparently
// decompresses gzip, and decodes into a Go string. UTF-8, UTF-16, US-ASCII,
// ISO-8859-1, and Windows-1252 are decoded natively; every other WHATWG label
// (GBK, Big5, Shift_JIS, EUC-JP/KR, ISO-2022-*, KOI8-*, UTF-32, …) is decoded via
// golang.org/x/text/encoding/htmlindex.
//
// It is the byte-level core extracted from a faithful port of jsoup's
// helper/DataUtil (jsoup-1.22.2); the markup-level charset discovery (reading a
// <meta charset> or <?xml encoding?> out of a parsed document) is left to the
// caller, which owns the parser.

// DefaultName is the fallback encoding name when nothing is detected.
const DefaultName = "UTF-8"

// DetectBOM inspects the leading bytes for a byte-order mark and returns the
// canonical encoding name it implies ("UTF-32", "UTF-16", or "UTF-8"), or "" if
// there is no BOM.
func DetectBOM(data []byte) string {
	if len(data) >= 4 &&
		((data[0] == 0x00 && data[1] == 0x00 && data[2] == 0xFE && data[3] == 0xFF) ||
			(data[0] == 0xFF && data[1] == 0xFE && data[2] == 0x00 && data[3] == 0x00)) {
		return "UTF-32"
	}
	if len(data) >= 2 &&
		((data[0] == 0xFE && data[1] == 0xFF) || (data[0] == 0xFF && data[1] == 0xFE)) {
		return "UTF-16"
	}
	if len(data) >= 3 && data[0] == 0xEF && data[1] == 0xBB && data[2] == 0xBF {
		return "UTF-8"
	}
	return ""
}

// Clean trims whitespace and surrounding single/double quotes from an encoding
// label. It returns "" when the input is blank.
func Clean(name string) string {
	name = strings.TrimSpace(name)
	name = strings.ReplaceAll(name, "\"", "")
	name = strings.ReplaceAll(name, "'", "")
	return strings.TrimSpace(name)
}

// FromContentType extracts the charset from a Content-Type-style header value,
// e.g. "text/html; charset=EUC-JP" -> "EUC-JP". Returns "" if absent. The name is
// cleaned (unquoted, trimmed).
func FromContentType(contentType string) string {
	if contentType == "" {
		return ""
	}
	return Clean(AttrValue(contentType, "charset"))
}

// AttrValue finds `key = value` in s (key matched case-insensitively, optional
// whitespace and optional single/double quotes around the value) and returns the
// raw value up to the next whitespace, comma, semicolon or quote. Returns "" if
// the key is not present. It covers both the charset= of a Content-Type header
// and the encoding= of an <?xml?> declaration.
func AttrValue(s, key string) string {
	ls := strings.ToLower(s)
	lk := strings.ToLower(key)
	from := 0
	for {
		idx := strings.Index(ls[from:], lk)
		if idx < 0 {
			return ""
		}
		j := from + idx + len(lk)
		for j < len(s) && (s[j] == ' ' || s[j] == '\t') {
			j++
		}
		if j < len(s) && s[j] == '=' {
			j++
			for j < len(s) && (s[j] == ' ' || s[j] == '\t') {
				j++
			}
			if j < len(s) && (s[j] == '"' || s[j] == '\'') {
				j++
			}
			start := j
			for j < len(s) {
				c := s[j]
				if c == ' ' || c == '\t' || c == '\n' || c == '\r' || c == ',' || c == ';' || c == '"' || c == '\'' {
					break
				}
				j++
			}
			if j > start {
				return s[start:j]
			}
		}
		from = from + idx + len(lk)
	}
}

// MaybeGunzip transparently decompresses gzip'd input (a leading 0x1f 0x8b),
// or returns the data unchanged.
func MaybeGunzip(data []byte) []byte {
	if len(data) >= 2 && data[0] == 0x1f && data[1] == 0x8b {
		if r, err := gzip.NewReader(bytes.NewReader(data)); err == nil {
			if out, rerr := io.ReadAll(r); rerr == nil {
				return out
			}
		}
	}
	return data
}

// Decode decodes data using the named encoding into a Go string. The native fast
// paths (UTF-8, UTF-16, US-ASCII/ISO-8859-1, Windows-1252) ignore punctuation and
// case in the name, so "iso-8859-1", "ISO8859_1" and "latin1" all fold together;
// any other name is decoded via the WHATWG registry (golang.org/x/text/encoding/
// htmlindex). A matching leading BOM is consumed. An unknown or undecodable name
// falls back to a best-effort UTF-8 decode.
func Decode(data []byte, name string) string {
	switch canonical(name) {
	case "utf-8":
		return decodeUtf8(data)
	case "utf-16":
		return decodeUtf16(data)
	case "ascii", "latin-1":
		return DecodeLatin1(stripUtf8Bom(data))
	case "windows-1252":
		return decodeWindows1252(data)
	}
	if enc, err := htmlindex.Get(name); err == nil {
		if decoded, derr := enc.NewDecoder().Bytes(data); derr == nil {
			return string(decoded)
		}
	}
	return decodeUtf8(data) // last-resort best effort
}

// canonical folds an encoding label to one of the native decode families, or ""
// if it is not one of them. Punctuation and case are ignored.
func canonical(name string) string {
	var b strings.Builder
	for _, r := range strings.ToUpper(name) {
		if (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
		}
	}
	switch b.String() {
	case "UTF8":
		return "utf-8"
	case "UTF16", "UTF16BE", "UTF16LE", "UNICODE":
		return "utf-16"
	case "USASCII", "ASCII", "ANSIX341968", "ISO646US":
		return "ascii"
	case "ISO88591", "LATIN1", "L1", "CP819", "IBM819", "8859", "88591", "ISOLATIN1":
		return "latin-1"
	case "WINDOWS1252", "CP1252", "1252", "MSANSI":
		return "windows-1252"
	}
	return ""
}

func stripUtf8Bom(data []byte) []byte {
	if len(data) >= 3 && data[0] == 0xEF && data[1] == 0xBB && data[2] == 0xBF {
		return data[3:]
	}
	return data
}

// decodeUtf8 returns data as a UTF-8 string, stripping a leading UTF-8 BOM.
func decodeUtf8(data []byte) string {
	return string(stripUtf8Bom(data))
}

// DecodeLatin1 maps each byte to the identically-numbered rune (ISO-8859-1 /
// US-ASCII) — the trivial single-byte decode. It is exported because it is the
// safe way to read a mostly-ASCII byte window (e.g. to sniff markup) without a
// high byte aborting the decode.
func DecodeLatin1(data []byte) string {
	var b strings.Builder
	b.Grow(len(data))
	for _, c := range data {
		b.WriteRune(rune(c))
	}
	return b.String()
}

// windows1252High maps the Windows-1252 0x80–0x9F block to its Unicode code
// points; the surrounding ranges coincide with ISO-8859-1.
var windows1252High = [32]rune{
	0x20AC, 0x0081, 0x201A, 0x0192, 0x201E, 0x2026, 0x2020, 0x2021,
	0x02C6, 0x2030, 0x0160, 0x2039, 0x0152, 0x008D, 0x017D, 0x008F,
	0x0090, 0x2018, 0x2019, 0x201C, 0x201D, 0x2022, 0x2013, 0x2014,
	0x02DC, 0x2122, 0x0161, 0x203A, 0x0153, 0x009D, 0x017E, 0x0178,
}

// decodeWindows1252 decodes the Windows-1252 (CP1252) single-byte code page.
func decodeWindows1252(data []byte) string {
	var b strings.Builder
	b.Grow(len(data))
	for _, c := range data {
		if c >= 0x80 && c <= 0x9F {
			b.WriteRune(windows1252High[c-0x80])
		} else {
			b.WriteRune(rune(c))
		}
	}
	return b.String()
}

// decodeUtf16 decodes UTF-16, choosing endianness from a leading BOM and
// defaulting to big-endian when there is none. The BOM is consumed.
func decodeUtf16(data []byte) string {
	bigEndian := true
	if len(data) >= 2 {
		if data[0] == 0xFE && data[1] == 0xFF {
			bigEndian = true
			data = data[2:]
		} else if data[0] == 0xFF && data[1] == 0xFE {
			bigEndian = false
			data = data[2:]
		}
	}
	units := make([]uint16, 0, len(data)/2)
	for i := 0; i+1 < len(data); i += 2 {
		if bigEndian {
			units = append(units, uint16(data[i])<<8|uint16(data[i+1]))
		} else {
			units = append(units, uint16(data[i+1])<<8|uint16(data[i]))
		}
	}
	return string(utf16.Decode(units))
}
