package goml_test

import (
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"goforge.dev/goplus/goml"
	"goforge.dev/goplus/internal/gen"
)

const optionGoml = `module option

-- Option carries one value or nothing.
type Option (a : Type) :=
  | Some (value : a)
  | None

let Map (f : a -> b) (o : Option a) : Option b :=
  match o with
  | Some v => Some (f v)
  | None => None
`

const vecGoml = `module vec

type Vec (a : Type) : Nat -> Type where
  | Nil : Vec a 0
  | Cons (head : a) (tail : Vec a n) : Vec a (n + 1)

let First : Vec a (n + 1) -> a
  | Cons h _ => h

let Concat (xs : Vec a n) (ys : Vec a m) : Vec a (n + m) :=
  match xs with
  | Nil => ys
  | Cons h t => Cons h (Concat t ys)
`

func write(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func runOK(t *testing.T, opts goml.Options) *goml.Result {
	t.Helper()
	res, err := goml.Run(opts)
	if err != nil {
		t.Fatal(err)
	}
	for _, d := range res.Diagnostics {
		t.Errorf("diagnostic: %s:%d:%d: %s", d.Filename, d.Line, d.Column, d.Message)
	}
	if t.Failed() {
		t.FailNow()
	}
	return res
}

func TestRunGeneratesFromGoml(t *testing.T) {
	dir := t.TempDir()
	write(t, filepath.Join(dir, "option.goml"), optionGoml)

	res := runOK(t, goml.Options{Dir: dir})
	if len(res.Converted) != 1 || res.Converted[0] != "option.goml" {
		t.Fatalf("Converted = %v", res.Converted)
	}
	out := filepath.Join(dir, "option_gml.go")
	src, err := os.ReadFile(out)
	if err != nil {
		t.Fatalf("expected %s: %v", out, err)
	}
	text := string(src)
	if !strings.HasPrefix(text, "// Code generated by goplus from option.goml. DO NOT EDIT.") {
		t.Fatalf("header does not name the .goml source:\n%s", text[:120])
	}
	if _, err := parser.ParseFile(token.NewFileSet(), out, src, 0); err != nil {
		t.Fatalf("generated file is not valid Go: %v", err)
	}
	if !strings.Contains(text, "goplus:enum") {
		t.Fatalf("generated file carries no enum markers:\n%s", text)
	}

	// A second run is a no-op; check mode agrees.
	res = runOK(t, goml.Options{Dir: dir})
	if len(res.Written) != 0 {
		t.Fatalf("second run rewrote %v", res.Written)
	}
	res = runOK(t, goml.Options{Dir: dir, Check: true})
	if len(res.Stale) != 0 {
		t.Fatalf("fresh output reported stale: %v", res.Stale)
	}
}

func TestCheckReportsStaleAndOrphans(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "option.goml")
	write(t, path, optionGoml)
	runOK(t, goml.Options{Dir: dir})

	// Edit the source: check mode reports the output stale.
	write(t, path, strings.Replace(optionGoml, "| None => None", "| None => o", 1))
	res := runOK(t, goml.Options{Dir: dir, Check: true})
	if len(res.Stale) != 1 {
		t.Fatalf("Stale = %v", res.Stale)
	}

	// Delete the source: the generated file is an orphan and goes away.
	if err := os.Remove(path); err != nil {
		t.Fatal(err)
	}
	res = runOK(t, goml.Options{Dir: dir})
	if len(res.Orphans) != 1 {
		t.Fatalf("Orphans = %v", res.Orphans)
	}
	if _, err := os.Stat(filepath.Join(dir, "option_gml.go")); !os.IsNotExist(err) {
		t.Fatalf("orphaned option_gml.go still present (err=%v)", err)
	}
}

// TestDifferentialParity is the M0 parity gate in miniature: the same
// program authored in .gp and .goml generates byte-identical Go modulo
// the generated-file header and the _gp/_gml suffix.
func TestDifferentialParity(t *testing.T) {
	gp, err := goml.Convert("vec.goml", []byte(vecGoml))
	if err != nil {
		t.Fatal(err)
	}

	gpDir := t.TempDir()
	write(t, filepath.Join(gpDir, "vec.gp"), string(gp))
	genRes, err := gen.Run(gen.Options{Dir: gpDir})
	if err != nil {
		t.Fatal(err)
	}
	for _, d := range genRes.Diags {
		t.Errorf(".gp twin diagnostic: %s", d)
	}
	if t.Failed() {
		t.FailNow()
	}

	gomlDir := t.TempDir()
	write(t, filepath.Join(gomlDir, "vec.goml"), vecGoml)
	runOK(t, goml.Options{Dir: gomlDir})

	fromGp, err := os.ReadFile(filepath.Join(gpDir, "vec_gp.go"))
	if err != nil {
		t.Fatal(err)
	}
	fromGoml, err := os.ReadFile(filepath.Join(gomlDir, "vec_gml.go"))
	if err != nil {
		t.Fatal(err)
	}
	normalize := func(b []byte) string {
		s := string(b)
		return strings.Replace(s, "from vec.gp.", "from vec.goml.", 1)
	}
	if normalize(fromGp) != normalize(fromGoml) {
		t.Fatalf("differential mismatch:\n--- from .gp ---\n%s\n--- from .goml ---\n%s", fromGp, fromGoml)
	}
}

const workerGoml = `module worker

type Msg :=
  | Inc (by : Int)
  | Halt

let Step (s : Int) (m : Msg) : Int :=
  match m with
  | Inc by => s + by
  | Halt => s

let Drain (inbox : Chan Msg) (done : Chan Bool) (s0 : Int) : Int := do {
  let mut s := s0;
  while true do {
    select with
    | m <- recv inbox => s := Step s m
    | _ <- recv done => return s
  };
  s
}
`

// TestDifferentialParityEffectful runs the M2 surface (do, select,
// while, mut) through both pipelines.
func TestDifferentialParityEffectful(t *testing.T) {
	gp, err := goml.Convert("worker.goml", []byte(workerGoml))
	if err != nil {
		t.Fatal(err)
	}
	gpDir := t.TempDir()
	write(t, filepath.Join(gpDir, "worker.gp"), string(gp))
	genRes, err := gen.Run(gen.Options{Dir: gpDir})
	if err != nil {
		t.Fatal(err)
	}
	for _, d := range genRes.Diags {
		t.Errorf(".gp twin diagnostic: %s", d)
	}
	if t.Failed() {
		t.FailNow()
	}
	gomlDir := t.TempDir()
	write(t, filepath.Join(gomlDir, "worker.goml"), workerGoml)
	runOK(t, goml.Options{Dir: gomlDir})

	fromGp, err := os.ReadFile(filepath.Join(gpDir, "worker_gp.go"))
	if err != nil {
		t.Fatal(err)
	}
	fromGoml, err := os.ReadFile(filepath.Join(gomlDir, "worker_gml.go"))
	if err != nil {
		t.Fatal(err)
	}
	normalize := func(b []byte) string {
		return strings.Replace(string(b), "from worker.gp.", "from worker.goml.", 1)
	}
	if normalize(fromGp) != normalize(fromGoml) {
		t.Fatalf("differential mismatch:\n--- from .gp ---\n%s\n--- from .goml ---\n%s", fromGp, fromGoml)
	}
	if _, err := parser.ParseFile(token.NewFileSet(), "worker_gml.go", fromGoml, 0); err != nil {
		t.Fatalf("generated file is not valid Go: %v", err)
	}
	if !strings.Contains(string(fromGoml), "select {") {
		t.Fatalf("select did not lower to native Go select:\n%s", fromGoml)
	}
}

// TestDiagnosticsMapToGomlLines: a pipeline diagnostic (non-exhaustive
// match) reports the .goml source line, not the lowered text's line.
func TestDiagnosticsMapToGomlLines(t *testing.T) {
	src := `module opt

type Option (a : Type) :=
  | Some (value : a)
  | None

let Get (o : Option Int) : Int :=
  match o with
  | Some v => v
`
	dir := t.TempDir()
	write(t, filepath.Join(dir, "go.mod"), "module opttest\n\ngo 1.26.0\n")
	write(t, filepath.Join(dir, "opt.goml"), src)
	res, err := goml.Run(goml.Options{Dir: dir})
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Diagnostics) == 0 {
		t.Fatal("expected a non-exhaustive match diagnostic")
	}
	d := res.Diagnostics[0]
	if !strings.HasSuffix(d.Filename, "opt.goml") {
		t.Fatalf("diagnostic filename = %q", d.Filename)
	}
	if !strings.Contains(d.Message, "non-exhaustive") {
		t.Fatalf("unexpected diagnostic: %s", d.Message)
	}
	// The match statement spans lines 8-9 of the .goml source; the
	// statement-grained map may land on either.
	if d.Line < 8 || d.Line > 9 {
		t.Fatalf("diagnostic line = %d, want 8 or 9 (the match)", d.Line)
	}
}
