// Code generated by gpp from algebra.gpp. DO NOT EDIT.

// Package algebra is the G++ algebraic hierarchy: eight classes from
// Magma to Group, related by embedding, with their laws declared where
// the structure earns them. Instances are law-tested by default; the
// generated tests live in the nested lawtest module so this package
// keeps zero dependencies.
//
//gpp:laws out=lawtest
package algebra

import "reflect"

// Magma is a closed binary operation. No laws: closure is the type
// system's job.
//
//gpp:class Magma[T any]
type Magma[T any] struct {
	Combine func(a, b T) T
}

// UnitalMagma is a magma with a two-sided identity.
//
//gpp:class UnitalMagma[T any] embeds(Magma)
type UnitalMagma[T any] struct {
	Combine func(a T, b T) T
	Empty   func() T
}

//gpp:law (UnitalMagma[T]) LeftId(a T)
func (m UnitalMagma[T]) LawLeftId(a T) bool { return reflect.DeepEqual(m.Combine(m.Empty(), a), a) }

//gpp:law (UnitalMagma[T]) RightId(a T)
func (m UnitalMagma[T]) LawRightId(a T) bool { return reflect.DeepEqual(m.Combine(a, m.Empty()), a) }

// Quasigroup is a magma with left and right division: LeftDiv(a, b)
// solves Combine(b, x) == a and RightDiv(a, b) solves Combine(x, b) == a.
//
//gpp:class Quasigroup[T any] embeds(Magma)
type Quasigroup[T any] struct {
	Combine  func(a T, b T) T
	LeftDiv  func(a, b T) T
	RightDiv func(a, b T) T
}

//gpp:law (Quasigroup[T]) LeftDivCancels(a, b T)
func (m Quasigroup[T]) LawLeftDivCancels(a, b T) bool {
	return reflect.DeepEqual(m.Combine(b, m.LeftDiv(a, b)), a)
}

//gpp:law (Quasigroup[T]) RightDivCancels(a, b T)
func (m Quasigroup[T]) LawRightDivCancels(a, b T) bool {
	return reflect.DeepEqual(m.Combine(m.RightDiv(a, b), b), a)
}

// Loop is a quasigroup with identity.
//
//gpp:class Loop[T any] embeds(UnitalMagma, Quasigroup)
type Loop[T any] struct {
	Combine  func(a T, b T) T
	Empty    func() T
	LeftDiv  func(a T, b T) T
	RightDiv func(a T, b T) T
}

// Semigroup is an associative magma.
//
//gpp:class Semigroup[T any] embeds(Magma)
type Semigroup[T any] struct {
	Combine func(a T, b T) T
}

//gpp:law (Semigroup[T]) Assoc(a, b, c T)
func (m Semigroup[T]) LawAssoc(a, b, c T) bool {
	return reflect.DeepEqual(m.Combine(m.Combine(a, b), c), m.Combine(a, m.Combine(b, c)))
}

// AssociativeQuasigroup is a quasigroup whose operation associates.
//
//gpp:class AssociativeQuasigroup[T any] embeds(Semigroup, Quasigroup)
type AssociativeQuasigroup[T any] struct {
	Combine  func(a T, b T) T
	LeftDiv  func(a T, b T) T
	RightDiv func(a T, b T) T
}

// Monoid is an associative unital magma.
//
//gpp:class Monoid[T any] embeds(Semigroup, UnitalMagma)
type Monoid[T any] struct {
	Combine func(a T, b T) T
	Empty   func() T
}

// Group is a monoid with inverses. Invertibility makes both divisions
// derivable, so Group carries their defaults: instances provide Combine,
// Empty, and Invert only.
//
//gpp:class Group[T any] embeds(Monoid, AssociativeQuasigroup)
type Group[T any] struct {
	Combine func(a T, b T) T
	Empty   func() T

	Invert   func(a T) T
	LeftDiv  func(a, b T) T
	RightDiv func(a, b T) T
}

//gpp:default (Group[T]) LeftDiv(a, b T)
func (m Group[T]) DefaultLeftDiv(a, b T) T { return m.Combine(m.Invert(b), a) }

//gpp:default (Group[T]) RightDiv(a, b T)
func (m Group[T]) DefaultRightDiv(a, b T) T { return m.Combine(a, m.Invert(b)) }

//gpp:law (Group[T]) LeftInverse(a T)
func (m Group[T]) LawLeftInverse(a T) bool {
	return reflect.DeepEqual(m.Combine(m.Invert(a), a), m.Empty())
}

//gpp:law (Group[T]) RightInverse(a T)
func (m Group[T]) LawRightInverse(a T) bool {
	return reflect.DeepEqual(m.Combine(a, m.Invert(a)), m.Empty())
}

// AsMagma views the UnitalMagma witness as its Magma part.
func (m UnitalMagma[T]) AsMagma() Magma[T] {
	return Magma[T]{Combine: m.Combine}
}

// AsMagma views the Quasigroup witness as its Magma part.
func (m Quasigroup[T]) AsMagma() Magma[T] {
	return Magma[T]{Combine: m.Combine}
}

// AsMagma views the Semigroup witness as its Magma part.
func (m Semigroup[T]) AsMagma() Magma[T] {
	return Magma[T]{Combine: m.Combine}
}

// AsUnitalMagma views the Loop witness as its UnitalMagma part.
func (m Loop[T]) AsUnitalMagma() UnitalMagma[T] {
	return UnitalMagma[T]{Combine: m.Combine, Empty: m.Empty}
}

// AsQuasigroup views the Loop witness as its Quasigroup part.
func (m Loop[T]) AsQuasigroup() Quasigroup[T] {
	return Quasigroup[T]{Combine: m.Combine, LeftDiv: m.LeftDiv, RightDiv: m.RightDiv}
}

// AsMagma views the Loop witness as its Magma part.
func (m Loop[T]) AsMagma() Magma[T] {
	return Magma[T]{Combine: m.Combine}
}

// AsSemigroup views the AssociativeQuasigroup witness as its Semigroup part.
func (m AssociativeQuasigroup[T]) AsSemigroup() Semigroup[T] {
	return Semigroup[T]{Combine: m.Combine}
}

// AsQuasigroup views the AssociativeQuasigroup witness as its Quasigroup part.
func (m AssociativeQuasigroup[T]) AsQuasigroup() Quasigroup[T] {
	return Quasigroup[T]{Combine: m.Combine, LeftDiv: m.LeftDiv, RightDiv: m.RightDiv}
}

// AsMagma views the AssociativeQuasigroup witness as its Magma part.
func (m AssociativeQuasigroup[T]) AsMagma() Magma[T] {
	return Magma[T]{Combine: m.Combine}
}

// AsSemigroup views the Monoid witness as its Semigroup part.
func (m Monoid[T]) AsSemigroup() Semigroup[T] {
	return Semigroup[T]{Combine: m.Combine}
}

// AsUnitalMagma views the Monoid witness as its UnitalMagma part.
func (m Monoid[T]) AsUnitalMagma() UnitalMagma[T] {
	return UnitalMagma[T]{Combine: m.Combine, Empty: m.Empty}
}

// AsMagma views the Monoid witness as its Magma part.
func (m Monoid[T]) AsMagma() Magma[T] {
	return Magma[T]{Combine: m.Combine}
}

// AsMonoid views the Group witness as its Monoid part.
func (m Group[T]) AsMonoid() Monoid[T] {
	return Monoid[T]{Combine: m.Combine, Empty: m.Empty}
}

// AsAssociativeQuasigroup views the Group witness as its AssociativeQuasigroup part.
func (m Group[T]) AsAssociativeQuasigroup() AssociativeQuasigroup[T] {
	return AssociativeQuasigroup[T]{Combine: m.Combine, LeftDiv: m.LeftDiv, RightDiv: m.RightDiv}
}

// AsSemigroup views the Group witness as its Semigroup part.
func (m Group[T]) AsSemigroup() Semigroup[T] {
	return Semigroup[T]{Combine: m.Combine}
}

// AsUnitalMagma views the Group witness as its UnitalMagma part.
func (m Group[T]) AsUnitalMagma() UnitalMagma[T] {
	return UnitalMagma[T]{Combine: m.Combine, Empty: m.Empty}
}

// AsQuasigroup views the Group witness as its Quasigroup part.
func (m Group[T]) AsQuasigroup() Quasigroup[T] {
	return Quasigroup[T]{Combine: m.Combine, LeftDiv: m.LeftDiv, RightDiv: m.RightDiv}
}

// AsMagma views the Group witness as its Magma part.
func (m Group[T]) AsMagma() Magma[T] {
	return Magma[T]{Combine: m.Combine}
}
