// Code generated by gpp from handlers.gpp. DO NOT EDIT.
//gpp:v v0.9.0

// The server's dispatch layer, authored in gpp: incoming work is an
// enum, routing is a match, and extending the server means adding a
// variant and an arm — the language serving itself.
package lsp

// Incoming is document-lifecycle work (notifications: no reply).
//
//gpp:enum Incoming
type Incoming interface{ isIncoming() }

//gpp:variant (Incoming) Opened(uri string, text string)
type Opened struct {
	Uri  string
	Text string
}

func (Opened) isIncoming() {}

//gpp:variant (Incoming) Changed(uri string, text string)
type Changed struct {
	Uri  string
	Text string
}

func (Changed) isIncoming() {}

//gpp:variant (Incoming) Closed(uri string)
type Closed struct {
	Uri string
}

func (Closed) isIncoming() {}

//gpp:variant (Incoming) Saved(uri string)
type Saved struct {
	Uri string
}

func (Saved) isIncoming() {}

// IncomingCases selects one handler per Incoming variant for IncomingFold.
type IncomingCases[R any] struct {
	Opened  func(uri string, text string) R
	Changed func(uri string, text string) R
	Closed  func(uri string) R
	Saved   func(uri string) R
}

// IncomingFold reduces Incoming by one-level case analysis.
func IncomingFold[R any](i Incoming, cs IncomingCases[R]) R {
	switch m := any(i).(type) {
	case Opened:
		return cs.Opened(m.Uri, m.Text)
	case Changed:
		return cs.Changed(m.Uri, m.Text)
	case Closed:
		return cs.Closed(m.Uri)
	case Saved:
		return cs.Saved(m.Uri)
	default:
		panic("gpp: impossible enum value in IncomingFold")
	}
}

// Dispatch routes lifecycle work onto the server.
func Dispatch(s *Server, in Incoming) {
	switch __gpp_m0 := any(in).(type) {
	case Opened:
		uri := __gpp_m0.Uri
		text := __gpp_m0.Text
		s.SetOverlay(uri, text)
		s.ScheduleDiagnostics()
	case Changed:
		uri := __gpp_m0.Uri
		text := __gpp_m0.Text
		s.SetOverlay(uri, text)
		s.ScheduleDiagnostics()
	case Closed:
		uri := __gpp_m0.Uri
		s.DropOverlay(uri)
	case Saved:
		uri := __gpp_m0.Uri
		_ = uri
		s.ScheduleDiagnostics()
	default:
		panic("gpp: impossible enum value in match")
	}
}

// Query is position work (requests: a reply is owed).
//
//gpp:enum Query
type Query interface{ isQuery() }

//gpp:variant (Query) QHover(uri string, line int, ch int)
type QHover struct {
	Uri  string
	Line int
	Ch   int
}

func (QHover) isQuery() {}

//gpp:variant (Query) QDefinition(uri string, line int, ch int)
type QDefinition struct {
	Uri  string
	Line int
	Ch   int
}

func (QDefinition) isQuery() {}

//gpp:variant (Query) QComplete(uri string, line int, ch int)
type QComplete struct {
	Uri  string
	Line int
	Ch   int
}

func (QComplete) isQuery() {}

// QueryCases selects one handler per Query variant for QueryFold.
type QueryCases[R any] struct {
	QHover      func(uri string, line int, ch int) R
	QDefinition func(uri string, line int, ch int) R
	QComplete   func(uri string, line int, ch int) R
}

// QueryFold reduces Query by one-level case analysis.
func QueryFold[R any](q Query, cs QueryCases[R]) R {
	switch m := any(q).(type) {
	case QHover:
		return cs.QHover(m.Uri, m.Line, m.Ch)
	case QDefinition:
		return cs.QDefinition(m.Uri, m.Line, m.Ch)
	case QComplete:
		return cs.QComplete(m.Uri, m.Line, m.Ch)
	default:
		panic("gpp: impossible enum value in QueryFold")
	}
}

// QueryReply is what a query yields: raw JSON from the delegate, or a
// reasoned absence (the client renders null).
//
//gpp:enum QueryReply
type QueryReply interface{ isQueryReply() }

//gpp:variant (QueryReply) Raw(data []byte)
type Raw struct {
	Data []byte
}

func (Raw) isQueryReply() {}

//gpp:variant (QueryReply) NoAnswer(reason string)
type NoAnswer struct {
	Reason string
}

func (NoAnswer) isQueryReply() {}

// QueryReplyCases selects one handler per QueryReply variant for QueryReplyFold.
type QueryReplyCases[R any] struct {
	Raw      func(data []byte) R
	NoAnswer func(reason string) R
}

// QueryReplyFold reduces QueryReply by one-level case analysis.
func QueryReplyFold[R any](q QueryReply, cs QueryReplyCases[R]) R {
	switch m := any(q).(type) {
	case Raw:
		return cs.Raw(m.Data)
	case NoAnswer:
		return cs.NoAnswer(m.Reason)
	default:
		panic("gpp: impossible enum value in QueryReplyFold")
	}
}

// Answer resolves one query through the gopls delegate.
func Answer(s *Server, q Query) QueryReply {
	switch __gpp_m1 := any(q).(type) {
	case QHover:
		uri := __gpp_m1.Uri
		line := __gpp_m1.Line
		ch := __gpp_m1.Ch
		return s.Forward("textDocument/hover", uri, line, ch)
	case QDefinition:
		uri := __gpp_m1.Uri
		line := __gpp_m1.Line
		ch := __gpp_m1.Ch
		return s.Forward("textDocument/definition", uri, line, ch)
	case QComplete:
		uri := __gpp_m1.Uri
		line := __gpp_m1.Line
		ch := __gpp_m1.Ch
		return s.Forward("textDocument/completion", uri, line, ch)
	default:
		panic("gpp: impossible enum value in match")
	}
}
