// Code generated by goplus from outcome.gp. DO NOT EDIT.
//goplus:v v0.28.0

// Terminal task/step lifecycle outcomes.
//
// The saga runner (workflow.gp) drives a forward sequence that knows only
// success or error. A task DAG needs a richer terminal state: a step may be
// Skipped because a precondition already made it unnecessary (up-to-date, gated
// off), run to Completion, or Fail. Outcome makes those three exhaustive — the
// "done | failed | skipped" typestate — without conflating a skip with a
// failure.
package workflow

// Outcome is the terminal lifecycle state of a task or step.
//
//goplus:enum Outcome
type Outcome interface{ isOutcome() }

// Skipped: a precondition made the step unnecessary (Reason explains which).
//
//goplus:variant (Outcome) Skipped(Reason string)
type Skipped struct {
	Reason string
}

func (Skipped) isOutcome() {}

// Completed: the step ran successfully.
//
//goplus:variant (Outcome) Completed()
type Completed struct{}

func (Completed) isOutcome() {}

// Failed: the step ran and errored.
//
//goplus:variant (Outcome) Failed(Err error)
type Failed struct {
	Err error
}

func (Failed) isOutcome() {}

// OutcomeCases selects one handler per Outcome variant for Fold.
type OutcomeCases[R any] struct {
	Skipped   func(Reason string) R
	Completed func() R
	Failed    func(Err error) R
}

// Fold reduces Outcome by one-level case analysis.
func Fold[R any](o Outcome, cs OutcomeCases[R]) R {
	switch m := any(o).(type) {
	case Skipped:
		return cs.Skipped(m.Reason)
	case Completed:
		return cs.Completed()
	case Failed:
		return cs.Failed(m.Err)
	default:
		panic("goplus: impossible enum value in Fold")
	}
}

// OutcomeEqOverrides carries optional per-variant hooks for OutcomeEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type OutcomeEqOverrides struct {
	Skipped   func(x, y Skipped) (eq, handled bool)
	Completed func(x, y Completed) (eq, handled bool)
	Failed    func(x, y Failed) (eq, handled bool)
}

// OutcomeEqualWith reports structural equality of a and b under ov.
func OutcomeEqualWith(a, b Outcome, ov OutcomeEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case Skipped:
		y, ok := any(b).(Skipped)
		if !ok {
			return false
		}
		if ov.Skipped != nil {
			if eq, handled := ov.Skipped(x, y); handled {
				return eq
			}
		}
		if x.Reason != y.Reason {
			return false
		}
		return true
	case Completed:
		y, ok := any(b).(Completed)
		if !ok {
			return false
		}
		if ov.Completed != nil {
			if eq, handled := ov.Completed(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case Failed:
		y, ok := any(b).(Failed)
		if !ok {
			return false
		}
		if ov.Failed != nil {
			if eq, handled := ov.Failed(x, y); handled {
				return eq
			}
		}
		if (x.Err == nil) != (y.Err == nil) {
			return false
		}
		if x.Err != nil && x.Err.Error() != y.Err.Error() {
			return false
		}
		return true
	}
	return false
}

// OutcomeEqual reports structural equality of a and b.
func OutcomeEqual(a, b Outcome) bool {
	return OutcomeEqualWith(a, b, OutcomeEqOverrides{})
}

// OutcomeError projects an Outcome onto Go's error convention: a Failed outcome
// yields its error; Skipped and Completed both yield nil, because a skipped step
// is not a failure.
func OutcomeError(o Outcome) error {
	switch __gp_m0 := any(o).(type) {
	case Failed:
		err := __gp_m0.Err

		return err
	case Skipped:

		return nil
	case Completed:

		return nil
	default:
		panic("goplus: impossible enum value in match")
	}
}

// Succeeded reports whether the outcome is non-failing (Completed or Skipped).
func Succeeded(o Outcome) bool {
	switch any(o).(type) {
	case Failed:

		return false
	default:

		return true
	}
}

// SkipReason returns the skip reason and true when the outcome is Skipped.
func SkipReason(o Outcome) (string, bool) {
	switch __gp_m2 := any(o).(type) {
	case Skipped:
		reason := __gp_m2.Reason

		return reason, true
	default:

		return "", false
	}
}
