// Code generated by goplus from vec.gp. DO NOT EDIT.
//goplus:v v0.28.0

// Package vec is a length-indexed sequence: Vec[T, n] carries its
// length in its type, so First and Rest exist only for non-empty
// vectors — the checker proves it, erasure drops it, and the generated
// Go stays a plain cons-list any Go program can use (guarded at the
// exported boundary).
package vec

//goplus:enum Vec[T any, n nat]
type Vec[T any] interface{ isVec(T) }

//goplus:variant (Vec[T]) Nil() Vec[T, 0]
type Nil[T any] struct{}

func (Nil[T]) isVec(T) {}

//goplus:variant (Vec[T]) Cons(Head T, Tail Vec[T, n]) Vec[T, n+1]
type Cons[T any] struct {
	Head T
	Tail Vec[T]
}

func (Cons[T]) isVec(T) {}

// VecCases selects one handler per Vec variant for VecFold.
type VecCases[T any, R any] struct {
	Nil  func() R
	Cons func(Head T, Tail Vec[T]) R
}

// VecFold reduces Vec[T] by one-level case analysis.
func VecFold[T any, R any](v Vec[T], cs VecCases[T, R]) R {
	switch m := any(v).(type) {
	case Nil[T]:
		return cs.Nil()
	case Cons[T]:
		return cs.Cons(m.Head, m.Tail)
	default:
		panic("goplus: impossible enum value in VecFold")
	}
}

// Pair is the shape-preserving product used by Zip.
type Pair[A any, B any] struct {
	First  A
	Second B
}

// Fin[n] is evidence that an index is strictly smaller than n.
//
//goplus:enum Fin[n nat]
type Fin interface{ isFin() }

//goplus:variant (Fin) Zero() Fin[n+1]
type Zero struct{}

func (Zero) isFin() {}

//goplus:variant (Fin) Succ(Prev Fin[n]) Fin[n+1]
type Succ struct {
	Prev Fin
}

func (Succ) isFin() {}

// FinCases selects one handler per Fin variant for FinFold.
type FinCases[R any] struct {
	Zero func() R
	Succ func(Prev Fin) R
}

// FinFold reduces Fin by one-level case analysis.
func FinFold[R any](f Fin, cs FinCases[R]) R {
	switch m := any(f).(type) {
	case Zero:
		return cs.Zero()
	case Succ:
		return cs.Succ(m.Prev)
	default:
		panic("goplus: impossible enum value in FinFold")
	}
}

// First returns the head of a non-empty vector. The Nil arm is
// impossible — the index says so, and now the source does too.
//
//goplus:dep First[T any](0 n nat, v Vec[T, n+1]) T
func First[T any](v Vec[T]) T {
	if _, ok := any(v).(Nil[T]); ok {
		panic("goplus: First: v with index n+1 cannot be Nil")
	}

	switch __gp_m0 := any(v).(type) {
	case Cons[T]:
		h := __gp_m0.Head
		t := __gp_m0.Tail

		_ = t
		return h
	default:
		panic("goplus: impossible enum value in match")
	}
}

// Rest returns everything after the head of a non-empty vector.
//
//goplus:dep Rest[T any](0 n nat, v Vec[T, n+1]) Vec[T, n]
func Rest[T any](v Vec[T]) Vec[T] {
	if _, ok := any(v).(Nil[T]); ok {
		panic("goplus: Rest: v with index n+1 cannot be Nil")
	}

	switch __gp_m1 := any(v).(type) {
	case Cons[T]:
		h := __gp_m1.Head
		t := __gp_m1.Tail

		_ = h
		return t
	default:
		panic("goplus: impossible enum value in match")
	}
}

// Length walks the spine; the result equals the index by construction.
//
//goplus:dep Length[T any](0 n nat, v Vec[T, n]) int
func Length[T any](v Vec[T]) int {
	total := 0
	switch __gp_m2 := any(v).(type) {
	case Nil[T]:

	case Cons[T]:
		h := __gp_m2.Head
		t := __gp_m2.Tail

		_ = h
		total = Length(t) + 1
	default:
		panic("goplus: impossible enum value in match")
	}
	return total
}

// Replicate builds the vector of n copies of x.
//
//goplus:dep Replicate[T any](n nat, x T) Vec[T, n]
func Replicate[T any](n int, x T) Vec[T] {
	if n == 0 {
		return Nil[T]{}
	}
	return Cons[T]{Head: x, Tail: Replicate(n-1, x)}
}

// Concat appends b to a; the indices add.
//
//goplus:dep Concat[T any](0 n nat, 0 m nat, a Vec[T, n], b Vec[T, m]) Vec[T, n+m]
func Concat[T any](a Vec[T], b Vec[T]) Vec[T] {
	switch __gp_m3 := any(a).(type) {
	case Nil[T]:

		return b
	case Cons[T]:
		h := __gp_m3.Head
		t := __gp_m3.Tail

		return Cons[T]{Head: h, Tail: Concat(t, b)}
	default:
		panic("goplus: impossible enum value in match")
	}
}

// Map transforms every element, preserving the length.
//
//goplus:dep Map[T any, U any](0 n nat, f func(T) U, v Vec[T, n]) Vec[U, n]
func Map[T any, U any](f func(T) U, v Vec[T]) Vec[U] {
	switch __gp_m4 := any(v).(type) {
	case Nil[T]:

		return Nil[U]{}
	case Cons[T]:
		h := __gp_m4.Head
		t := __gp_m4.Tail

		return Cons[U]{Head: f(h), Tail: Map(f, t)}
	default:
		panic("goplus: impossible enum value in match")
	}
}

// Zip requires equal shapes and preserves that shape in its result.
//
//goplus:dep Zip[A any, B any](0 n nat, left Vec[A, n], right Vec[B, n]) Vec[Pair[A, B], n]
func Zip[A any, B any](left Vec[A], right Vec[B]) Vec[Pair[A, B]] {
	if Length(left) != Length(right) {
		panic("vec.Zip: vectors have different lengths")
	}
	return zipSame(left, right)
}

//goplus:dep zipSame[A any, B any](0 n nat, left Vec[A, n], right Vec[B, n]) Vec[Pair[A, B], n]
func zipSame[A any, B any](left Vec[A], right Vec[B]) Vec[Pair[A, B]] {
	switch __gp_m5 := any(left).(type) {
	case Nil[A]:

		_ = right
		return Nil[Pair[A, B]]{}
	case Cons[A]:
		a := __gp_m5.Head
		as := __gp_m5.Tail

		return Cons[Pair[A, B]]{Head: Pair[A, B]{First: a, Second: First(right)}, Tail: zipSame(as, Rest(right))}
	default:
		panic("goplus: impossible enum value in match")
	}
}

// At is total: Fin[n] makes an out-of-bounds index unrepresentable in Go+.
//
//goplus:dep At[T any](0 n nat, index Fin[n], values Vec[T, n]) T
func At[T any](index Fin, values Vec[T]) T {
	switch __gp_m6 := any(index).(type) {
	case Zero:

		return First(values)
	case Succ:
		previous := __gp_m6.Prev

		return At(previous, Rest(values))
	default:
		panic("goplus: impossible enum value in match")
	}
}

// AtIndex selects by an ordinary number rather than Peano evidence. The
// bound travels as a proposition, so it is proved at the call and then
// erased: no Fin to build, and an out-of-range index is a compile error
// rather than a panic. Prefer Fin when the evidence is already in hand
// (recursing over an index), and AtIndex when you have a plain number.
//
//goplus:dep AtIndex[T any](i nat, 0 n nat, 0 p Lt[i, n], values Vec[T, n]) T
func AtIndex[T any](i int, values Vec[T]) T {
	if _, ok := any(values).(Nil[T]); ok {
		panic("goplus: AtIndex: values with index n cannot be Nil")
	}

	switch __gp_m7 := any(values).(type) {
	case Cons[T]:
		h := __gp_m7.Head
		t := __gp_m7.Tail

		if i == 0 {
			return h
		}
		return AtIndex(i-1, t)
	default:
		panic("goplus: impossible enum value in match")
	}
}

// Set replaces the element at i, the dual of AtIndex and bounded the
// same way. The length is preserved, so the result keeps its index.
//
//goplus:dep Set[T any](i nat, 0 n nat, 0 p Lt[i, n], x T, values Vec[T, n]) Vec[T, n]
func Set[T any](i int, x T, values Vec[T]) Vec[T] {
	if _, ok := any(values).(Nil[T]); ok {
		panic("goplus: Set: values with index n cannot be Nil")
	}

	switch __gp_m8 := any(values).(type) {
	case Cons[T]:
		h := __gp_m8.Head
		t := __gp_m8.Tail

		if i == 0 {
			return Cons[T]{Head: x, Tail: t}
		}
		return Cons[T]{Head: h, Tail: Set(i-1, x, t)}
	default:
		panic("goplus: impossible enum value in match")
	}
}
