Feature: goml, the ML-family surface
  goml (spec/goml-design.md) is a second front end over the Go+ core: a
  .goml source transpiles to .gp text and generates through the ordinary
  pipeline, emitting <file>_gml.go beside it. These scenarios twin their
  .gp counterparts: same core semantics, second spelling.

  Background:
    Given a file "go.mod":
      """
      module example.com/demo

      go 1.24
      """

  Scenario: A sum type and exhaustive match generate from goml
    Given a file "option.goml":
      """
      module option

      type Option (a : Type) :=
        | Some (value : a)
        | None

      let UnwrapOr (o : Option a) (d : a) : a :=
        match o with
        | Some v => v
        | None => d
      """
    When I run goml with arguments "gen ."
    Then the exit code is 0
    And the file "option_gml.go" is valid Go
    And the file "option_gml.go" contains "// Code generated by goplus from option.goml. DO NOT EDIT."
    And the file "option_gml.go" contains "goplus:enum Option[a any]"
    And the file "option_gml.go" contains "func UnwrapOr[a any]"

  Scenario: The dependent core erases goml indices
    Given a file "vec.goml":
      """
      module vec

      type Vec (a : Type) : Nat -> Type where
        | Nil : Vec a 0
        | Cons (head : a) (tail : Vec a n) : Vec a (n + 1)

      let First : Vec a (n + 1) -> a
        | Cons h _ => h
      """
    When I run goml with arguments "gen ."
    Then the exit code is 0
    And the file "vec_gml.go" is valid Go
    And the file "vec_gml.go" contains "func First[a any](v Vec[a]) a"
    And the file "vec_gml.go" does not contain "func First[a any](n nat"

  Scenario: A named proposition declares, erases, and prunes from goml
    Given a file "vec.goml":
      """
      module vec

      type Vec (a : Type) : Nat -> Type where
        | Nil : Vec a 0
        | Cons (head : a) (tail : Vec a n) : Vec a (n + 1)

      type InRange (i : Nat) (n : Nat) := prop { And (Le 0 i) (Lt i n) }

      let At {0 i n : Nat} (0 p : InRange i n) (v : Vec a n) : a :=
        match v with
        | Cons h _ => h

      let Pick (v : Vec Int 3) : Int :=
        At 1 3 decide v
      """
    When I run goml with arguments "gen ."
    Then the exit code is 0
    And the file "vec_gml.go" is valid Go
    And the file "vec_gml.go" contains "//goplus:prop InRange[i, n] And[Le[0, i], Lt[i, n]]"
    And the file "vec_gml.go" does not contain "prop {"
    And the file "vec_gml.go" contains:
      """
      panic("goplus: At: v with index n cannot be Nil")
      """

  Scenario: A goml interface declares natively and feeds delegation
    Given a file "store.goml":
      """
      module store

      type Store := interface {
        Get : String -> Int;
        Len : Unit -> Int
      }

      type Cache := { inner : Store @[delegate]; hits : Int }
      """
    When I run goml with arguments "gen ."
    Then the exit code is 0
    And the file "store_gml.go" is valid Go
    And the file "store_gml.go" contains "type Store interface {"
    And the file "store_gml.go" contains "//goplus:delegate Cache.inner"
    And the file "store_gml.go" contains "func (c Cache) Get(p0 string) int { return c.inner.Get(p0) }"
    And the file "store_gml.go" contains "func (c Cache) Len() int { return c.inner.Len() }"

  Scenario: Expected types flow to lambdas, list literals, and where-helpers lower privately
    Given a file "pipeline.goml":
      """
      module pipeline

      let Apply (f : Int -> Int) (xs : Slice Int) : Int :=
        sum xs (f 1)
        where sum (ys : Slice Int) (seed : Int) : Int := do {
          let mut t := seed;
          for _, y in ys do { t := t + y };
          t
        }

      let Run () : Int := Apply (fun x => x * 2) [3, 4, 5]
      """
    When I run goml with arguments "gen ."
    Then the exit code is 0
    And the file "pipeline_gml.go" is valid Go
    And the file "pipeline_gml.go" contains "func Run() int {"
    And the file "pipeline_gml.go" contains "Apply(func(x int) int { return x * 2 }, []int{3, 4, 5})"
    And the file "pipeline_gml.go" contains "func sum(ys []int, seed int) int {"

  Scenario: open exposing and user operators generate through the pipeline
    Given a module "example.com/demo" using the goplus standard library
    And a file "railway.goml":
      """
      module railway

      import "goforge.dev/goplus/std/result"
      open result exposing (Result, Ok, Err)

      infixl 5 <+> := Merge

      let Merge (a b : Int) : Int := a + b

      let Sum (a b c : Int) : Result Int Error :=
        Ok (a <+> b <+> c)
      """
    When I run goml with arguments "gen ."
    Then the exit code is 0
    And the file "railway_gml.go" is valid Go
    And the file "railway_gml.go" contains "result.Ok[int, error]{Value: Merge(Merge(a, b), c)}"

  Scenario: Option pipelines lift from goml too
    Given a module "example.com/demo" using the goplus standard library
    And a file "maybe.goml":
      """
      module maybe

      import "goforge.dev/goplus/std/option"
      open option exposing (Option, Some)

      let Half (n : Int) : Option Int :=
        if n % 2 == 0 then Some (n / 2) else option.Of 0 false

      let Walk (n : Int) : Int :=
        Some n |> Half |> Half |> .UnwrapOr 0
      """
    When I run goml with arguments "gen ."
    Then the exit code is 0
    And the file "maybe_gml.go" is valid Go
    And the file "maybe_gml.go" contains "option.Bind"
    And the file "maybe_gml.go" contains "option.UnwrapOr"

  Scenario: An impossible arm asserts pruning from goml and emits nothing
    Given a file "vec.goml":
      """
      module vec

      type Vec (a : Type) : Nat -> Type where
        | Nil : Vec a 0
        | Cons (head : a) (tail : Vec a n) : Vec a (n + 1)

      let First : Vec a (n + 1) -> a
        | Cons h _ => h
        | Nil => impossible
      """
    When I run goml with arguments "gen ."
    Then the exit code is 0
    And the file "vec_gml.go" is valid Go
    And the file "vec_gml.go" contains:
      """
      panic("goplus: First: v with index n+1 cannot be Nil")
      """

  Scenario: A reachable impossible arm is refused with a goml position
    Given a file "vec.goml":
      """
      module vec

      type Vec (a : Type) : Nat -> Type where
        | Nil : Vec a 0
        | Cons (head : a) (tail : Vec a n) : Vec a (n + 1)

      let Sum (v : Vec Int n) : Int :=
        match v with
        | Cons h _ => h
        | Nil => impossible
      """
    When I run goml with arguments "gen ."
    Then the exit code is 2
    And stderr contains "this arm is not impossible"

  Scenario: Guards flip on in goml and lower to guarded arms
    Given a file "shape.goml":
      """
      module shape

      type Shape :=
        | Circle (r : Int)
        | Rect (w : Int) (h : Int)

      let Classify (s : Shape) : String :=
        match s with
        | Circle r if r > 10 => "big"
        | Circle _ => "small"
        | Rect w h if w == h => "square"
        | Rect _ _ => "rect"
      """
    When I run goml with arguments "gen ."
    Then the exit code is 0
    And the file "shape_gml.go" is valid Go
    And the file "shape_gml.go" contains "if r > 10 {"

  Scenario: Literal patterns prove coverage from goml hypotheses
    Given a file "names.goml":
      """
      module names

      let Name (n : Nat) (0 p : Lt n 3) : String :=
        match n with
        | 0 => "zero"
        | 1 => "one"
        | 2 => "two"
      """
    When I run goml with arguments "gen ."
    Then the exit code is 0
    And the file "names_gml.go" is valid Go
    And the file "names_gml.go" contains:
      """
      panic("goplus: match on n: value outside the proven range")
      """

  Scenario: do blocks and select lower to native Go statements
    Given a file "worker.goml":
      """
      module worker

      let Drain (inbox : Chan Int) (done : Chan Bool) (s0 : Int) : Int := do {
        let mut s := s0;
        while true do {
          select with
          | m <- recv inbox => s := s + m
          | _ <- recv done => return s
        };
        s
      }
      """
    When I run goml with arguments "gen ."
    Then the exit code is 0
    And the file "worker_gml.go" is valid Go
    And the file "worker_gml.go" contains "select {"
    And the file "worker_gml.go" contains "case m := <-inbox:"

  Scenario: Check mode reports stale goml output and exits 1
    Given a file "option.goml":
      """
      module option

      type Option (a : Type) :=
        | Some (value : a)
        | None
      """
    When I run goml with arguments "gen ."
    Then the exit code is 0
    When I run goml with arguments "gen -check ."
    Then the exit code is 0
    Given a file "option.goml":
      """
      module option

      type Option (a : Type) :=
        | Some (value : a)
        | None2
      """
    When I run goml with arguments "gen -check ."
    Then the exit code is 1
    And stdout contains "option_gml.go"

  Scenario: Deleting the goml source orphans its generated file
    Given a file "option.goml":
      """
      module option

      type Option (a : Type) :=
        | Some (value : a)
        | None
      """
    When I run goml with arguments "gen ."
    Then the exit code is 0
    When the file "option.goml" is deleted
    And I run goml with arguments "gen ."
    Then the exit code is 0
    And the file "option_gml.go" does not exist

  Scenario: A plain goplus run leaves goml sources and outputs alone
    Given a file "option.goml":
      """
      module option

      type Option (a : Type) :=
        | Some (value : a)
        | None
      """
    When I run goml with arguments "gen ."
    Then the exit code is 0
    When I run goplus with arguments "gen ."
    Then the exit code is 0
    And the file "option_gml.go" contains "goplus:enum"

  Scenario: goml transpile errors are positioned in the goml source
    Given a file "bad.goml":
      """
      module bad

      let X := match y with | 1.5 => 1
      """
    When I run goml with arguments "gen ."
    Then the exit code is 2
    And stderr contains "bad.goml:3"
    And stderr contains "expected a pattern"

  Scenario: goml reports its version
    When I run goml with arguments "version"
    Then the exit code is 0
    And stdout contains "goml version v"

  Scenario: A mixed package generates both surfaces in one run
    Given a file "shape.goml":
      """
      module mixed

      type Shape :=
        | Circle (r : Int)
        | Rect (w : Int) (h : Int)
      """
    And a file "area.gp":
      """
      package mixed

      func Area(s Shape) int {
      	match s {
      	case Circle(r):
      		return 3 * r * r
      	case Rect(w, h):
      		return w * h
      	}
      }
      """
    When I run goml with arguments "gen ."
    Then the exit code is 0
    And the file "shape_gml.go" is valid Go
    And the file "area_gp.go" is valid Go
    And the file "area_gp.go" contains "// Code generated by goplus from area.gp. DO NOT EDIT."

  Scenario: Type-indexed GADTs and record literals generate from goml
    Given a file "typed.goml":
      """
      module typed

      type Expr : Type -> Type where
        | Lit (v : Int) : Expr Int
        | Truth (b : Bool) : Expr Bool

      type Settings := { Port : Int; Host : String }

      let Make (p : Int) (h : String) : Settings :=
        Settings { Port = p, Host = h }

      let Negate (b : Bool) : Bool := !b
      """
    When I run goml with arguments "gen ."
    Then the exit code is 0
    And the file "typed_gml.go" is valid Go
    And the file "typed_gml.go" contains "goplus:variant (Expr[a]) Lit(v int) Expr[int]"
    And the file "typed_gml.go" contains "return Settings{Port: p, Host: h}"
    And the file "typed_gml.go" contains "return !b"

  Scenario: A nullary goml let binds a package-level value
    Given a module "example.com/values" using the goplus standard library
    And a file "conf.goml":
      """
      module conf

      type Color :=
        | Red
        | Green

      let Port := 8080

      let NextPort : Int := Port + 1

      let Current : Color := Red

      let Describe (c : Color) : String :=
        match c with
        | Red => "red"
        | Green => "green"

      let CurrentName : String := Describe Current

      let Start () : Unit := println CurrentName
      """
    When I run goml with arguments "gen ."
    Then the exit code is 0
    And the file "conf_gml.go" is valid Go
    And the file "conf_gml.go" contains "var Port = 8080"
    And the file "conf_gml.go" contains "var NextPort int = Port + 1"
    And the file "conf_gml.go" does not contain "func Port()"
    And the file "conf_gml.go" contains "func Start()"

  Scenario: A package-level value cannot hold a match body
    Given a file "bad.goml":
      """
      module bad

      type T :=
        | A
        | B

      let S : T := A

      let V : Int := match S with | A => 1 | B => 2
      """
    When I run goml with arguments "gen ."
    Then the exit code is 2
    And stderr contains "bad.goml:9"
    And stderr contains "cannot hoist at package level"

  Scenario: A typed hole reports its goal at the hole, keeping the indices
    Given a file "go.mod":
      """
      module example.com/demo

      go 1.24
      """
    And a file "vec.goml":
      """
      module vec

      type Vec (a : Type) : Nat -> Type where
        | Nil : Vec a 0
        | Cons (head : a) (tail : Vec a n) : Vec a (n + 1)

      let Rest {0 n : Nat} (v : Vec a (n + 1)) : Vec a n :=
        ?rest
      """
    When I run goml with arguments "gen ."
    Then the exit code is 2
    And stderr contains "vec.goml:8:3: hole ?rest : Vec a n"
    And stderr contains "n : Nat (erased, quantity 0)"
    And the file "vec_gml.go" does not exist

  Scenario: Hole names must be unique within a file
    Given a file "dup.goml":
      """
      module dup

      let F (a : Int) (b : Int) : Int := ?gap + ?gap
      """
    When I run goml with arguments "gen ."
    Then the exit code is 2
    And stderr contains "hole ?gap already appears"
    And the file "dup_gml.go" does not exist
