Feature: goml, the ML-family surface
  goml (spec/goml-design.md) is a second front end over the Go+ core: a
  .goml source transpiles to .gp text and generates through the ordinary
  pipeline, emitting <file>_gml.go beside it. These scenarios twin their
  .gp counterparts: same core semantics, second spelling.

  Scenario: A sum type and exhaustive match generate from goml
    Given a file "option.goml":
      """
      module option

      type Option (a : Type) :=
        | Some (value : a)
        | None

      let UnwrapOr (o : Option a) (d : a) : a :=
        match o with
        | Some v => v
        | None => d
      """
    When I run goml with arguments "gen ."
    Then the exit code is 0
    And the file "option_gml.go" is valid Go
    And the file "option_gml.go" contains "// Code generated by goplus from option.goml. DO NOT EDIT."
    And the file "option_gml.go" contains "goplus:enum Option[a any]"
    And the file "option_gml.go" contains "func UnwrapOr[a any]"

  Scenario: The dependent core erases goml indices
    Given a file "vec.goml":
      """
      module vec

      type Vec (a : Type) : Nat -> Type where
        | Nil : Vec a 0
        | Cons (head : a) (tail : Vec a n) : Vec a (n + 1)

      let First : Vec a (n + 1) -> a
        | Cons h _ => h
      """
    When I run goml with arguments "gen ."
    Then the exit code is 0
    And the file "vec_gml.go" is valid Go
    And the file "vec_gml.go" contains "func First[a any](v Vec[a]) a"
    And the file "vec_gml.go" does not contain "func First[a any](n nat"

  Scenario: do blocks and select lower to native Go statements
    Given a file "worker.goml":
      """
      module worker

      let Drain (inbox : Chan Int) (done : Chan Bool) (s0 : Int) : Int := do {
        let mut s := s0;
        while true do {
          select with
          | m <- recv inbox => s := s + m
          | _ <- recv done => return s
        };
        s
      }
      """
    When I run goml with arguments "gen ."
    Then the exit code is 0
    And the file "worker_gml.go" is valid Go
    And the file "worker_gml.go" contains "select {"
    And the file "worker_gml.go" contains "case m := <-inbox:"

  Scenario: Check mode reports stale goml output and exits 1
    Given a file "option.goml":
      """
      module option

      type Option (a : Type) :=
        | Some (value : a)
        | None
      """
    When I run goml with arguments "gen ."
    Then the exit code is 0
    When I run goml with arguments "gen -check ."
    Then the exit code is 0
    Given a file "option.goml":
      """
      module option

      type Option (a : Type) :=
        | Some (value : a)
        | None2
      """
    When I run goml with arguments "gen -check ."
    Then the exit code is 1
    And stdout contains "option_gml.go"

  Scenario: Deleting the goml source orphans its generated file
    Given a file "option.goml":
      """
      module option

      type Option (a : Type) :=
        | Some (value : a)
        | None
      """
    When I run goml with arguments "gen ."
    Then the exit code is 0
    When the file "option.goml" is deleted
    And I run goml with arguments "gen ."
    Then the exit code is 0
    And the file "option_gml.go" does not exist

  Scenario: A plain goplus run leaves goml sources and outputs alone
    Given a file "option.goml":
      """
      module option

      type Option (a : Type) :=
        | Some (value : a)
        | None
      """
    When I run goml with arguments "gen ."
    Then the exit code is 0
    When I run goplus with arguments "gen ."
    Then the exit code is 0
    And the file "option_gml.go" contains "goplus:enum"

  Scenario: goml transpile errors are positioned in the goml source
    Given a file "bad.goml":
      """
      module bad

      let X := match y with | 0 => 1
      """
    When I run goml with arguments "gen ."
    Then the exit code is 2
    And stderr contains "bad.goml:3"
    And stderr contains "expected a pattern"

  Scenario: goml reports its version
    When I run goml with arguments "version"
    Then the exit code is 0
    And stdout contains "goml version v"

  Scenario: A mixed package generates both surfaces in one run
    Given a file "shape.goml":
      """
      module mixed

      type Shape :=
        | Circle (r : Int)
        | Rect (w : Int) (h : Int)
      """
    And a file "area.gp":
      """
      package mixed

      func Area(s Shape) int {
      	match s {
      	case Circle(r):
      		return 3 * r * r
      	case Rect(w, h):
      		return w * h
      	}
      }
      """
    When I run goml with arguments "gen ."
    Then the exit code is 0
    And the file "shape_gml.go" is valid Go
    And the file "area_gp.go" is valid Go
    And the file "area_gp.go" contains "// Code generated by goplus from area.gp. DO NOT EDIT."
