package javabackend

// RuntimeSources is the versioned Java runtime ABI used by thin Go+ module
// jars. Keeping it in generated source makes bootstrap builds reproducible;
// release packaging compiles the same bytes into goplus-runtime-abi1.jar.
func RuntimeSources() map[string][]byte {
	return map[string][]byte{
		"module-info.java": []byte(gpRuntimeModuleSource),
		"GpString.java":    []byte(gpStringSource),
		"GpSlice.java":     []byte(gpSliceSource),
		"GpMap.java":       []byte(gpMapSource),
		"GpRef.java":       []byte(gpRefSource),
		"GpCopy.java":      []byte(gpCopySource),
		"GpError.java":     []byte(gpErrorSource),
		"GpChan.java":      []byte(gpChanSource),
		"GpSelect.java":    []byte(gpSelectSource),
		"GpRuntime.java":   []byte(gpRuntimeSource),
		"GpTest.java":      []byte(gpTestSource),
		"GpFn0.java":       []byte(gpFn0Source),
		"GpFn1.java":       []byte(gpFn1Source),
		"GpFn2.java":       []byte(gpFn2Source),
		"GpFn3.java":       []byte(gpFn3Source),
		"GpTuple2.java":    []byte(gpTuple2Source),
		"GpTuple3.java":    []byte(gpTuple3Source),
	}
}

const gpRuntimeModuleSource = `// Code generated by goplus (Java runtime ABI 1). DO NOT EDIT.
module dev.goforge.goplus.runtime {
    exports dev.goforge.goplus.runtime;
}
`

const runtimeHeader = `// Code generated by goplus (Java runtime ABI 1). DO NOT EDIT.
package dev.goforge.goplus.runtime;

`

const gpStringSource = runtimeHeader + `import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.Base64;

/** Go string: immutable arbitrary bytes, not a Java UTF-16 string. */
public final class GpString implements Comparable<GpString> {
    public static final GpString EMPTY = new GpString(new byte[0], false);
    private final byte[] bytes;

    private GpString(byte[] bytes, boolean copy) {
        this.bytes = copy ? bytes.clone() : bytes;
    }

    public static GpString fromBytes(byte[] bytes) {
        return bytes.length == 0 ? EMPTY : new GpString(bytes, true);
    }

    public static GpString fromBase64(String encoded) {
        byte[] decoded = Base64.getDecoder().decode(encoded);
        return decoded.length == 0 ? EMPTY : new GpString(decoded, false);
    }

    /** Explicit Java boundary conversion using UTF-8. */
    public static GpString fromJava(String value) {
        return fromBytes(value.getBytes(StandardCharsets.UTF_8));
    }

    /** Explicit Java boundary conversion; malformed UTF-8 is replaced per the JDK decoder. */
    public String toJava() {
        return new String(bytes, StandardCharsets.UTF_8);
    }

    public byte[] bytes() { return bytes.clone(); }
    public int byteLength() { return bytes.length; }
    public int byteAt(int index) { return Byte.toUnsignedInt(bytes[index]); }

    public GpString slice(int low, int high) {
        if (low < 0 || high < low || high > bytes.length) {
            throw GpRuntime.panicValue("slice bounds out of range");
        }
        return fromBytes(Arrays.copyOfRange(bytes, low, high));
    }

    public GpString concat(GpString other) {
        if (bytes.length == 0) return other;
        if (other.bytes.length == 0) return this;
        byte[] out = Arrays.copyOf(bytes, bytes.length + other.bytes.length);
        System.arraycopy(other.bytes, 0, out, bytes.length, other.bytes.length);
        return new GpString(out, false);
    }

    @Override public int compareTo(GpString other) {
        return Arrays.compareUnsigned(bytes, other.bytes);
    }

    @Override public boolean equals(Object other) {
        return other instanceof GpString value && Arrays.equals(bytes, value.bytes);
    }

    @Override public int hashCode() { return Arrays.hashCode(bytes); }
    @Override public String toString() { return toJava(); }
}
`

const gpSliceSource = runtimeHeader + `import java.util.Arrays;
import java.util.Iterator;
import java.util.NoSuchElementException;
import java.util.function.Supplier;
import java.util.function.UnaryOperator;

/** Go slice header over a shared backing array. */
public final class GpSlice<T> implements Iterable<T> {
    private Object[] array;
    private int offset;
    private int length;
    private int capacity;
    private final Supplier<T> zero;
	private final UnaryOperator<T> copier;
	private final boolean arrayValue;

	private GpSlice(Object[] array, int offset, int length, int capacity, Supplier<T> zero, UnaryOperator<T> copier, boolean arrayValue) {
        this.array = array;
        this.offset = offset;
        this.length = length;
        this.capacity = capacity;
        this.zero = zero;
		this.copier = copier;
		this.arrayValue = arrayValue;
    }

    public static <T> GpSlice<T> nil(Supplier<T> zero, UnaryOperator<T> copier) {
		return new GpSlice<>(null, 0, 0, 0, zero, copier, false);
    }

    public static <T> GpSlice<T> make(int length, int capacity, Supplier<T> zero, UnaryOperator<T> copier) {
        if (length < 0 || capacity < length) throw GpRuntime.panicValue("makeslice: len out of range");
        Object[] values = new Object[capacity];
		for (int i = 0; i < capacity; i++) values[i] = zero.get();
		return new GpSlice<>(values, 0, length, capacity, zero, copier, false);
	}

	public static <T> GpSlice<T> makeArray(int length, Supplier<T> zero, UnaryOperator<T> copier) {
		if (length < 0) throw GpRuntime.panicValue("array length out of range");
		Object[] values = new Object[length];
		for (int i = 0; i < length; i++) values[i] = zero.get();
		return new GpSlice<>(values, 0, length, length, zero, copier, true);
    }

    @SafeVarargs @SuppressWarnings("varargs")
    public static <T> GpSlice<T> ofZero(Supplier<T> zero, UnaryOperator<T> copier, T... values) {
		return new GpSlice<>(values.clone(), 0, values.length, values.length, zero, copier, false);
	}

	@SafeVarargs @SuppressWarnings("varargs")
	public static <T> GpSlice<T> ofArray(Supplier<T> zero, UnaryOperator<T> copier, T... values) {
		return new GpSlice<>(values.clone(), 0, values.length, values.length, zero, copier, true);
    }

    public boolean isNil() { return array == null; }
    public int length() { return length; }
    public int capacity() { return capacity; }

    @SuppressWarnings("unchecked")
    public T get(int index) {
        bounds(index);
        return (T) array[offset + index];
    }

    public void set(int index, T value) {
        bounds(index);
        array[offset + index] = value;
    }

    public GpSlice<T> slice(int low, int high) {
        if (low < 0 || high < low || high > capacity) throw GpRuntime.panicValue("slice bounds out of range");
		return new GpSlice<>(array, offset + low, high - low, capacity - low, zero, copier, false);
    }

    public GpSlice<T> appended(T value) {
        GpSlice<T> result = copyHeader();
        return result.appendInPlace(value);
    }

    public GpSlice<T> appendedAll(GpSlice<T> values) {
        GpSlice<T> result = copyHeader();
		Object[] snapshot = values.toArray();
		for (Object raw : snapshot) {
			@SuppressWarnings("unchecked") T value = (T) raw;
			result.appendInPlace(result.copier.apply(value));
		}
        return result;
    }

    private GpSlice<T> appendInPlace(T value) {
        if (length < capacity) {
            array[offset + length] = value;
            length++;
            return this;
        }
        int next = capacity == 0 ? 1 : capacity + Math.max(capacity, 1);
        Object[] grown = new Object[next];
        if (length > 0) System.arraycopy(array, offset, grown, 0, length);
        array = grown;
        offset = 0;
        capacity = next;
        array[length++] = value;
        return this;
    }

    public GpSlice<T> copyHeader() {
		return new GpSlice<>(array, offset, length, capacity, zero, copier, arrayValue);
	}

	public boolean isArrayValue() { return arrayValue; }

	public GpSlice<T> copyArray() {
		Object[] copied = new Object[length];
		for (int i = 0; i < length; i++) copied[i] = copier.apply(get(i));
		return new GpSlice<>(copied, 0, length, length, zero, copier, true);
    }

	public T copyElement(T value) { return copier.apply(value); }

    public Object[] toArray() {
        return length == 0 ? new Object[0] : Arrays.copyOfRange(array, offset, offset + length);
    }

    public void clear() {
        for (int i = offset; i < offset + length; i++) array[i] = zero.get();
    }

    private void bounds(int index) {
        if (index < 0 || index >= length) throw GpRuntime.panicValue("index out of range");
    }

    @Override public Iterator<T> iterator() {
        return new Iterator<>() {
            private int index;
            @Override public boolean hasNext() { return index < length; }
            @Override public T next() {
                if (!hasNext()) throw new NoSuchElementException();
                return get(index++);
            }
        };
    }

	@Override public boolean equals(Object other) {
		if (!arrayValue || !(other instanceof GpSlice<?> value) || !value.arrayValue || length != value.length) return false;
		for (int i = 0; i < length; i++) {
			if (!GpRuntime.equal(array[offset + i], value.array[value.offset + i])) return false;
		}
		return true;
	}

	@Override public int hashCode() {
		if (!arrayValue) return System.identityHashCode(this);
		int hash = 1;
		for (int i = 0; i < length; i++) hash = 31 * hash + GpRuntime.hash(array[offset + i]);
		return hash;
	}
}
`

const gpMapSource = runtimeHeader + `import java.util.AbstractMap;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Set;
import java.util.function.Supplier;

/** Go map handle. */
public final class GpMap<K, V> {
	private static final class Key<K> {
		private final K value;
		private Key(K value) { this.value = value; }
		@Override public boolean equals(Object other) {
			return other instanceof Key<?> key && GpRuntime.equal(value, key.value);
		}
		@Override public int hashCode() { return GpRuntime.hash(value); }
	}

    private final Map<Key<K>, V> values;
    private final boolean nil;
    private final Supplier<V> zero;

    private GpMap(Map<Key<K>, V> values, boolean nil, Supplier<V> zero) {
        this.values = values;
        this.nil = nil;
        this.zero = zero;
    }

    public static <K, V> GpMap<K, V> nil(Supplier<V> zero) {
        return new GpMap<>(new LinkedHashMap<>(), true, zero);
    }
    public static <K, V> GpMap<K, V> make(Supplier<V> zero) {
        return new GpMap<>(new LinkedHashMap<>(), false, zero);
    }
    @SafeVarargs public static <K, V> GpMap<K, V> of(Supplier<V> zero, GpTuple2<K, V>... entries) {
        GpMap<K, V> result = make(zero);
        for (GpTuple2<K, V> entry : entries) result.put(entry.first(), entry.second());
        return result;
    }
    public boolean isNil() { return nil; }
    public int length() { return values.size(); }
    public V get(K key) {
		Key<K> wrapped = new Key<>(key);
		return values.containsKey(wrapped) ? values.get(wrapped) : zero.get();
	}
    public GpTuple2<V, Boolean> lookup(K key) {
		Key<K> wrapped = new Key<>(key);
		return new GpTuple2<>(values.containsKey(wrapped) ? values.get(wrapped) : zero.get(), values.containsKey(wrapped));
	}
    public void put(K key, V value) {
        if (nil) throw GpRuntime.panicValue("assignment to entry in nil map");
		values.put(new Key<>(GpRuntime.copy(key)), value);
    }
    public void delete(K key) { values.remove(new Key<>(key)); }
    public void clear() { values.clear(); }
    public Set<Map.Entry<K, V>> entries() {
		Set<Map.Entry<K, V>> result = new LinkedHashSet<>();
		for (Map.Entry<Key<K>, V> entry : values.entrySet()) {
			result.add(new AbstractMap.SimpleImmutableEntry<>(entry.getKey().value, entry.getValue()));
		}
		return result;
	}
}
`

const gpRefSource = runtimeHeader + `/** Explicit mutable cell used for Go pointer identity. */
public final class GpRef<T> {
    private T value;
    public GpRef(T value) { this.value = value; }
    public T get() { return value; }
    public void set(T value) { this.value = value; }
}
`

const gpCopySource = runtimeHeader + `/** Implemented by generated Go value types that require copy semantics. */
public interface GpCopy<T> { T copy(); }
`

const gpErrorSource = runtimeHeader + `/** Go's built-in error interface. */
@FunctionalInterface
public interface GpError { GpString Error(); }
`

const gpFn0Source = runtimeHeader + `@FunctionalInterface
public interface GpFn0<R> { R apply(); }
`

const gpFn1Source = runtimeHeader + `@FunctionalInterface
public interface GpFn1<A, R> { R apply(A a); }
`

const gpFn2Source = runtimeHeader + `@FunctionalInterface
public interface GpFn2<A, B, R> { R apply(A a, B b); }
`

const gpFn3Source = runtimeHeader + `@FunctionalInterface
public interface GpFn3<A, B, C, R> { R apply(A a, B b, C c); }
`

const gpTuple2Source = runtimeHeader + `public record GpTuple2<A, B>(A first, B second) {}
`

const gpTuple3Source = runtimeHeader + `public record GpTuple3<A, B, C>(A first, B second, C third) {}
`

const gpChanSource = runtimeHeader + `import java.util.ArrayDeque;
import java.util.Deque;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.NoSuchElementException;
import java.util.concurrent.locks.Condition;
import java.util.concurrent.locks.ReentrantLock;
import java.util.function.Supplier;

/** Go channel with FIFO send/receive queues and close semantics. */
public final class GpChan<T> implements Iterable<T> {
    static final ReentrantLock SELECT_LOCK = new ReentrantLock(true);
    static final Condition CHANGED = SELECT_LOCK.newCondition();

    private static final class Sender<T> {
        private final T value;
        private boolean taken;
        private Sender(T value) { this.value = value; }
    }

    private final int capacity;
    private final Supplier<T> zero;
	private final boolean nil;
	private final Deque<T> buffer = new LinkedList<>();
    private final Deque<Sender<T>> senders = new ArrayDeque<>();
    private int waitingReceivers;
    private boolean closed;

    private GpChan(int capacity, Supplier<T> zero, boolean nil) {
        if (capacity < 0) throw GpRuntime.panicValue("makechan: size out of range");
        this.capacity = capacity;
        this.zero = zero;
		this.nil = nil;
    }

    public static <T> GpChan<T> make(int capacity, Supplier<T> zero) {
		return new GpChan<>(capacity, zero, false);
    }

	public static <T> GpChan<T> nil() { return new GpChan<>(0, () -> null, true); }

    public void send(T value) {
        SELECT_LOCK.lock();
        try {
			while (nil) awaitChange();
            if (closed) throw GpRuntime.panicValue("send on closed channel");
            if (capacity > 0) {
                while (buffer.size() == capacity) {
                    awaitChange();
                    if (closed) throw GpRuntime.panicValue("send on closed channel");
                }
                buffer.addLast(value);
                CHANGED.signalAll();
                return;
            }
            Sender<T> sender = new Sender<>(value);
            senders.addLast(sender);
            CHANGED.signalAll();
            while (!sender.taken) {
                if (closed) {
                    senders.remove(sender);
                    throw GpRuntime.panicValue("send on closed channel");
                }
                awaitChange();
            }
        } finally {
            SELECT_LOCK.unlock();
        }
    }

    public T receive() { return receiveOk().first(); }

    public GpTuple2<T, Boolean> receiveOk() {
        SELECT_LOCK.lock();
        try {
			while (nil) awaitChange();
            waitingReceivers++;
            CHANGED.signalAll();
            try {
                while (!receiveReady()) awaitChange();
                return receiveNow();
            } finally {
                waitingReceivers--;
                CHANGED.signalAll();
            }
        } finally {
            SELECT_LOCK.unlock();
        }
    }

    public void close() {
        SELECT_LOCK.lock();
        try {
			if (nil) throw GpRuntime.panicValue("close of nil channel");
            if (closed) throw GpRuntime.panicValue("close of closed channel");
            closed = true;
            CHANGED.signalAll();
        } finally {
            SELECT_LOCK.unlock();
        }
    }

    public int length() {
        SELECT_LOCK.lock();
		try { return nil ? 0 : buffer.size(); }
        finally { SELECT_LOCK.unlock(); }
    }

	public int capacity() { return nil ? 0 : capacity; }
	public boolean isNil() { return nil; }

    boolean sendReady() {
		return !nil && (closed || (capacity > 0 ? buffer.size() < capacity : waitingReceivers > 0));
    }

	boolean receiveReady() { return !nil && (!buffer.isEmpty() || !senders.isEmpty() || closed); }

    void sendNow(T value) {
        if (closed) throw GpRuntime.panicValue("send on closed channel");
        if (capacity > 0) {
            buffer.addLast(value);
        } else {
            senders.addLast(new Sender<>(value));
        }
        CHANGED.signalAll();
    }

    GpTuple2<T, Boolean> receiveNow() {
        if (!buffer.isEmpty()) {
            T value = buffer.removeFirst();
            CHANGED.signalAll();
            return new GpTuple2<>(value, true);
        }
        if (!senders.isEmpty()) {
            Sender<T> sender = senders.removeFirst();
            sender.taken = true;
            CHANGED.signalAll();
            return new GpTuple2<>(sender.value, true);
        }
        return new GpTuple2<>(zero.get(), false);
    }

    static void awaitChange() {
        try {
            CHANGED.await();
        } catch (InterruptedException interrupted) {
            Thread.currentThread().interrupt();
            throw GpRuntime.panicValue("channel operation interrupted");
        }
    }

    @Override public Iterator<T> iterator() {
        return new Iterator<>() {
            private GpTuple2<T, Boolean> next;
            @Override public boolean hasNext() {
                if (next == null) next = receiveOk();
                return next.second();
            }
            @Override public T next() {
                if (!hasNext()) throw new NoSuchElementException();
                T value = next.first();
                next = null;
                return value;
            }
        };
    }
}
`

const gpSelectSource = runtimeHeader + `import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ThreadLocalRandom;

/** Atomic channel selection. Readiness and commitment share the channel lock. */
public final class GpSelect {
    private GpSelect() {}

    public sealed interface Case<T> permits Send, Receive, Default {}
    public record Send<T>(GpChan<T> channel, T value) implements Case<T> {}
    public record Receive<T>(GpChan<T> channel) implements Case<T> {}
    public record Default<T>() implements Case<T> {}
    public record Selection(int index, Object value, boolean ok) {}

    public static Selection select(List<? extends Case<?>> cases) {
        GpChan.SELECT_LOCK.lock();
        try {
            for (;;) {
                List<Integer> ready = new ArrayList<>();
                int fallback = -1;
                for (int i = 0; i < cases.size(); i++) {
                    Case<?> item = cases.get(i);
                    if (item instanceof Send<?> send && send.channel().sendReady()) ready.add(i);
                    else if (item instanceof Receive<?> receive && receive.channel().receiveReady()) ready.add(i);
                    else if (item instanceof Default<?>) fallback = i;
                }
                if (!ready.isEmpty()) {
                    int index = ready.get(ThreadLocalRandom.current().nextInt(ready.size()));
                    return commit(index, cases.get(index));
                }
                if (fallback >= 0) return new Selection(fallback, null, false);
                GpChan.awaitChange();
            }
        } finally {
            GpChan.SELECT_LOCK.unlock();
        }
    }

    private static Selection commit(int index, Case<?> item) {
        if (item instanceof Send<?> send) {
            sendUnchecked(send);
            return new Selection(index, null, true);
        }
        if (item instanceof Receive<?> receive) {
            GpTuple2<?, Boolean> result = receive.channel().receiveNow();
            return new Selection(index, result.first(), result.second());
        }
        return new Selection(index, null, false);
    }

    private static <T> void sendUnchecked(Send<T> send) {
        send.channel().sendNow(send.value());
    }
}
`

const gpRuntimeSource = runtimeHeader + `import java.util.ArrayDeque;
import java.util.Deque;
import java.util.Objects;

/** Semantic helpers shared by generated Java packages. */
public final class GpRuntime {
    private GpRuntime() {}

	private static final class JavaError implements GpError {
		private final Throwable cause;
		private JavaError(Throwable cause) { this.cause = cause; }
		@Override public GpString Error() {
			String message = cause.getMessage();
			return GpString.fromJava(message == null ? cause.getClass().getName() : message);
		}
		@Override public String toString() { return Error().toJava(); }
	}

    @SuppressWarnings("serial")
    public static final class GpPanic extends RuntimeException {
        private static final long serialVersionUID = 1L;
        private final Object value;
        private GpPanic(Object value) {
            super(String.valueOf(value));
            this.value = value;
        }
        public Object value() { return value; }
    }

    public static GpPanic panicValue(Object value) { return new GpPanic(value); }
    public static void panic(Object value) { throw panicValue(value); }
    public static <T> T panicExpr(Object value) { throw panicValue(value); }
	public static GpError javaError(Throwable value) {
		if (value instanceof GpError error) return error;
		return new JavaError(value);
	}

    public static Thread go(Runnable body) { return Thread.startVirtualThread(body); }

    public static void print(Object... values) {
        for (Object value : values) System.out.print(show(value));
    }

    public static void println(Object... values) {
        for (int i = 0; i < values.length; i++) {
            if (i > 0) System.out.print(' ');
            System.out.print(show(values[i]));
        }
        System.out.println();
    }

    public static String show(Object value) {
        if (value == null) return "<nil>";
        if (value instanceof GpString text) return text.toJava();
		if (value instanceof GpError error) return error.Error().toJava();
        return Objects.toString(value);
    }

    public static long length(GpString value) { return value.byteLength(); }
    public static long length(GpSlice<?> value) { return value.length(); }
    public static long length(GpMap<?, ?> value) { return value.length(); }
    public static long length(GpChan<?> value) { return value.length(); }

    public static long capacity(GpSlice<?> value) { return value.capacity(); }
    public static long capacity(GpChan<?> value) { return value.capacity(); }

	public static int index(long value) {
		if (value < Integer.MIN_VALUE || value > Integer.MAX_VALUE) throw panicValue("integer does not fit Java collection index");
		return (int) value;
	}

	public static byte int8(long value) { return (byte) value; }
	public static byte int8(double value) { return (byte) value; }
	public static short int16(long value) { return (short) value; }
	public static short int16(double value) { return (short) value; }
	public static int int32(long value) { return (int) value; }
	public static int int32(double value) { return (int) value; }
	public static int uint8(long value) { return (int) value & 0xff; }
	public static int uint8(double value) { return (int) (long) value & 0xff; }
	public static int uint16(long value) { return (int) value & 0xffff; }
	public static int uint16(double value) { return (int) (long) value & 0xffff; }
	public static long uint32(long value) { return value & 0xffff_ffffL; }
	public static long uint32(double value) { return (long) value & 0xffff_ffffL; }
	public static float float32(double value) { return (float) value; }

	public static GpString stringFromRune(long value) {
		int rune = (int) value;
		if (value != rune || !Character.isValidCodePoint(rune) || rune >= 0xd800 && rune <= 0xdfff) rune = 0xfffd;
		return GpString.fromJava(new String(Character.toChars(rune)));
	}

	public static GpString stringFromBytes(GpSlice<Integer> values) {
		byte[] bytes = new byte[values.length()];
		for (int i = 0; i < bytes.length; i++) bytes[i] = (byte) (int) values.get(i);
		return GpString.fromBytes(bytes);
	}

	public static GpString stringFromRunes(GpSlice<Integer> values) {
		StringBuilder text = new StringBuilder();
		for (int value : values) {
			int rune = Character.isValidCodePoint(value) && !(value >= 0xd800 && value <= 0xdfff) ? value : 0xfffd;
			text.appendCodePoint(rune);
		}
		return GpString.fromJava(text.toString());
	}

	public static GpSlice<Integer> bytesFromString(GpString value) {
		byte[] bytes = value.bytes();
		GpSlice<Integer> out = GpSlice.make(bytes.length, bytes.length, () -> 0, item -> item);
		for (int i = 0; i < bytes.length; i++) out.set(i, Byte.toUnsignedInt(bytes[i]));
		return out;
	}

	public static GpSlice<Integer> runesFromString(GpString value) {
		int[] runes = value.toJava().codePoints().toArray();
		GpSlice<Integer> out = GpSlice.make(runes.length, runes.length, () -> 0, item -> item);
		for (int i = 0; i < runes.length; i++) out.set(i, runes[i]);
		return out;
	}

    public static <T> long copySlice(GpSlice<T> destination, GpSlice<T> source) {
        int count = Math.min(destination.length(), source.length());
        Object[] temporary = source.toArray();
        for (int i = 0; i < count; i++) {
            @SuppressWarnings("unchecked") T value = (T) temporary[i];
            destination.set(i, destination.copyElement(value));
        }
        return count;
    }

    public static void clear(GpSlice<?> value) { value.clear(); }
    public static void clear(GpMap<?, ?> value) { value.clear(); }

    @SuppressWarnings("unchecked")
    public static <T> T copy(T value) {
        if (value instanceof GpCopy<?> copied) return (T) copied.copy();
		if (value instanceof GpSlice<?> slice) return (T) (slice.isArrayValue() ? slice.copyArray() : slice.copyHeader());
        return value;
    }

    public static boolean equal(Object left, Object right) {
		if (left == null) return right == null;
		if (right == null) return false;
		if (left instanceof Double a && right instanceof Double b) return a.doubleValue() == b.doubleValue();
		if (left instanceof Float a && right instanceof Float b) return a.floatValue() == b.floatValue();
		return left.equals(right);
	}

    public static int hash(Object value) {
        if (value instanceof Double number && number == 0.0) return 0;
        if (value instanceof Float number && number == 0.0f) return 0;
        return Objects.hashCode(value);
    }

    public static <T> T requireNonNull(T value, String boundary) {
        if (value == null) throw panicValue("Java boundary returned null: " + boundary);
        return value;
    }

    public static long shiftLeft(long value, long count) {
		if (count < 0) throw panicValue("negative shift amount");
        return count >= 64 ? 0L : value << count;
    }

    public static long shiftRight(long value, long count) {
		if (count < 0) throw panicValue("negative shift amount");
        return count >= 64 ? (value < 0 ? -1L : 0L) : value >> count;
    }

    public static long shiftRightUnsigned(long value, long count) {
		if (count < 0) throw panicValue("negative shift amount");
        return count >= 64 ? 0L : value >>> count;
    }

	public static long minUnsigned(long left, long right) {
		return Long.compareUnsigned(left, right) <= 0 ? left : right;
	}

	public static long maxUnsigned(long left, long right) {
		return Long.compareUnsigned(left, right) >= 0 ? left : right;
	}

	public static GpString minString(GpString left, GpString right) {
		return left.compareTo(right) <= 0 ? left : right;
	}

	public static GpString maxString(GpString left, GpString right) {
		return left.compareTo(right) >= 0 ? left : right;
	}

    private static final ThreadLocal<Deque<Runnable>> DEFERS = new ThreadLocal<>();

    public static DeferScope deferScope() {
        Deque<Runnable> parent = DEFERS.get();
        Deque<Runnable> local = new ArrayDeque<>();
        DEFERS.set(local);
        return new DeferScope(parent, local);
    }

    public static void defer(Runnable action) {
        Deque<Runnable> stack = DEFERS.get();
        if (stack == null) throw new IllegalStateException("defer outside generated function scope");
        stack.push(action);
    }

    public static final class DeferScope implements AutoCloseable {
        private final Deque<Runnable> parent;
        private final Deque<Runnable> local;
        private DeferScope(Deque<Runnable> parent, Deque<Runnable> local) {
            this.parent = parent;
            this.local = local;
        }
		public void touch() {}
        @Override public void close() {
            Throwable first = null;
            while (!local.isEmpty()) {
                try { local.pop().run(); }
                catch (Throwable thrown) { if (first == null) first = thrown; }
            }
            DEFERS.set(parent);
            if (first instanceof RuntimeException runtime) throw runtime;
            if (first instanceof Error error) throw error;
            if (first != null) throw new RuntimeException(first);
        }
    }
}
`

const gpTestSource = runtimeHeader + `import java.io.IOException;
import java.nio.file.Files;
import java.util.ArrayDeque;
import java.util.Deque;
import java.util.function.Consumer;

/** Minimal semantic adapter for ordinary func TestX(t *testing.T) tests. */
public final class GpTest {
    @SuppressWarnings("serial")
    private static final class Abort extends RuntimeException {}
    @SuppressWarnings("serial")
    private static final class Skip extends RuntimeException {}

    private final String name;
    private final Deque<GpFn0<Void>> cleanups = new ArrayDeque<>();
    private boolean failed;

    private GpTest(String name) { this.name = name; }

    public static int run(String name, Consumer<GpTest> body) {
        System.out.println("=== RUN   " + name);
        GpTest test = new GpTest(name);
        boolean skipped = false;
        try {
            body.accept(test);
        } catch (Skip skip) {
            skipped = true;
        } catch (Abort abort) {
            // Failure was already recorded.
        } catch (Throwable thrown) {
            test.failed = true;
            thrown.printStackTrace(System.err);
        } finally {
            while (!test.cleanups.isEmpty()) {
                try { test.cleanups.pop().apply(); }
                catch (Throwable thrown) { test.failed = true; thrown.printStackTrace(System.err); }
            }
        }
        String status = skipped ? "SKIP" : test.failed ? "FAIL" : "PASS";
        System.out.println("--- " + status + ": " + name);
        return test.failed ? 1 : 0;
    }

    public void Helper() {}
    public void Parallel() {}
    public GpString Name() { return GpString.fromJava(name); }
    public boolean Failed() { return failed; }
    public void Fail() { failed = true; }
    public void FailNow() { failed = true; throw new Abort(); }
    public void Error(GpSlice<Object> args) { failed = true; log(args); }
    public void Errorf(GpString format, GpSlice<Object> args) { failed = true; System.err.println(format(format, args)); }
    public void Fatal(GpSlice<Object> args) { Error(args); throw new Abort(); }
    public void Fatalf(GpString format, GpSlice<Object> args) { Errorf(format, args); throw new Abort(); }
    public void Log(GpSlice<Object> args) { log(args); }
    public void Logf(GpString format, GpSlice<Object> args) { System.out.println(format(format, args)); }
    public void Skip(GpSlice<Object> args) { log(args); throw new Skip(); }
    public void Skipf(GpString format, GpSlice<Object> args) { System.out.println(format(format, args)); throw new Skip(); }
    public void SkipNow() { throw new Skip(); }
    public void Cleanup(GpFn0<Void> cleanup) { cleanups.push(cleanup); }

    public boolean Run(GpString childName, GpFn1<GpTest, Void> body) {
        String fullName = name + "/" + childName.toJava();
        int result = run(fullName, child -> body.apply(child));
        if (result != 0) failed = true;
        return result == 0;
    }

    public GpString TempDir() {
        try { return GpString.fromJava(Files.createTempDirectory("goplus-test-").toString()); }
        catch (IOException error) { Fatalf(GpString.fromJava("TempDir: %s"), GpSlice.ofZero(() -> null, value -> value, error)); return GpString.EMPTY; }
    }

    private static void log(GpSlice<Object> args) {
        StringBuilder text = new StringBuilder();
        for (Object arg : args) {
            if (text.length() > 0) text.append(' ');
            text.append(GpRuntime.show(arg));
        }
        System.err.println(text);
    }

    private static String format(GpString format, GpSlice<Object> args) {
        String template = format.toJava().replace("%v", "%s").replace("%q", "%s");
        return String.format(template, args.toArray());
    }
}
`
