Feature: Cross-package UX (v0.9.0)
  Generated files carry a //gpp:v vintage stamp and a toolchain refuses
  files from its future with an upgrade hint. Marker reconstruction is
  package-wide, index domains cross packages, Eq propositions resolve
  in the callee's scope, and a missing instance names the transitive
  package that would provide one.

  Background:
    Given a file "go.mod":
      """
      module example.com/demo

      go 1.24
      """

  Scenario: Generated files carry the toolchain vintage
    Given a G++ file "main.gpp":
      """
      package main

      func main() {
      	s := "hi" |> func(x string) string { return x + "!" }
      	println(s)
      }
      """
    When I run gpp with arguments "gen ."
    Then the exit code is 0
    And the file "main_gpp.go" contains:
      """
      //gpp:v v
      """

  Scenario: A file generated by a newer gpp refuses with an upgrade hint
    Given a file "lib/lib.go":
      """
      // Code generated by gpp from lib.gpp. DO NOT EDIT.
      //gpp:v v99.0.0

      package lib

      //gpp:method (Box) Widen
      func Widen() {}
      """
    And a G++ file "main.gpp":
      """
      package main

      import "example.com/demo/lib"

      func main() {
      	lib.Widen()
      }
      """
    When I run gpp with arguments "gen ."
    Then the exit code is 2
    And stderr contains "was generated by gpp v99.0.0"
    And stderr contains "upgrade with: go install goforge.dev/gpp/cmd/gpp@v99.0.0"

  Scenario: Dependency reconstruction crosses files within a package
    Given a G++ file "net/state.gpp":
      """
      package net

      type State enum {
      	Open
      	Closed
      }
      """
    And a G++ file "net/socket.gpp":
      """
      package net

      type Socket[s State] enum {
      	Fresh() Socket[Open]
      	Done(Reason string) Socket[Closed]
      }
      """
    And a G++ file "main.gpp":
      """
      package main

      import (
      	"fmt"

      	"example.com/demo/net"
      )

      func describe(s net.Socket[net.Open]) string {
      	match s {
      	case net.Fresh():
      		return "fresh"
      	}
      }

      func main() {
      	fmt.Println(describe(net.Fresh()))
      }
      """
    When I run gpp with arguments "gen ./net"
    Then the exit code is 0
    When I run gpp with arguments "gen ."
    Then the exit code is 0
    When I run gpp with arguments "run ."
    Then the exit code is 0
    And stdout contains "fresh"

  Scenario: An index domain imported from another package
    Given a G++ file "states/states.gpp":
      """
      package states

      type State enum {
      	Open
      	Closed
      }
      """
    And a G++ file "net/net.gpp":
      """
      package net

      import "example.com/demo/states"

      type Socket[s states.State] enum {
      	Fresh() Socket[states.Open]
      	Done(Reason string) Socket[states.Closed]
      }
      """
    And a G++ file "main.gpp":
      """
      package main

      import (
      	"fmt"

      	"example.com/demo/net"
      	"example.com/demo/states"
      )

      func describe(s net.Socket[states.Open]) string {
      	match s {
      	case net.Fresh():
      		return "fresh"
      	}
      }

      func main() {
      	fmt.Println(describe(net.Fresh()))
      }
      """
    When I run gpp with arguments "gen ./..."
    Then the exit code is 0
    When I run gpp with arguments "run ."
    Then the exit code is 0
    And stdout contains "fresh"
    And the file "net/net_gpp.go" contains:
      """
      //gpp:enum Socket[s states.State]
      """

  Scenario: An imported Eq proposition unfolds the callee's totals
    Given a G++ file "arith/arith.gpp":
      """
      package arith

      type Vec[T any, n nat] enum {
      	Nil() Vec[T, 0]
      	Cons(Head T, Tail Vec[T, n]) Vec[T, n+1]
      }

      total func Plus(a, b nat) nat {
      	if a == 0 {
      		return b
      	}
      	return Plus(a-1, b) + 1
      }

      func Cast[T any](0 n nat, 0 m nat, 0 p Eq[Plus(n, 1), m], v Vec[T, n]) Vec[T, m] {
      	return Cons(zeroOf(v), v)
      }

      func zeroOf[T any](v Vec[T]) T {
      	var z T
      	_ = v
      	return z
      }
      """
    And a G++ file "main.gpp":
      """
      package main

      import (
      	"fmt"

      	"example.com/demo/arith"
      )

      func main() {
      	v := arith.Cons(7, arith.Nil[int]())
      	w := arith.Cast(1, 2, refl, v)
      	_ = w
      	fmt.Println("cast ok")
      }
      """
    When I run gpp with arguments "gen ./..."
    Then the exit code is 0
    When I run gpp with arguments "run ."
    Then the exit code is 0
    And stdout contains "cast ok"

  Scenario: A missing instance names the transitive provider
    Given a G++ file "shapes/shapes.gpp":
      """
      package shapes

      type Sized[T any] class {
      	Size(x T) int
      }

      func Total[T Sized](xs []T) int {
      	t := 0
      	for _, x := range xs {
      		t += Size(x)
      	}
      	return t
      }
      """
    And a G++ file "impls/impls.gpp":
      """
      package impls

      import "example.com/demo/shapes"

      instance StringSize shapes.Sized[string] {
      	Size(x string) int { return len(x) }
      }
      """
    And a G++ file "mid/mid.gpp":
      """
      package mid

      import (
      	"example.com/demo/impls"
      	"example.com/demo/shapes"
      )

      func Use() int {
      	return shapes.Total(impls.StringSize, []string{"a"})
      }
      """
    And a G++ file "main.gpp":
      """
      package main

      import (
      	"fmt"

      	"example.com/demo/mid"
      	"example.com/demo/shapes"
      )

      func main() {
      	fmt.Println(mid.Use())
      	fmt.Println(shapes.Total([]string{"ab", "c"}))
      }
      """
    When I run gpp with arguments "gen ./..."
    Then the exit code is 2
    And stderr contains "no instance of Sized[string] is in scope"
    And stderr contains:
      """
      note: example.com/demo/impls exports StringSize, which matches; import "example.com/demo/impls" to bring it into scope
      """
