// Code generated by goplus from scan.gp. DO NOT EDIT.
//goplus:v v0.28.0

package scan

import (
	"strings"
	"unicode"
)

// Package scan is a buffered rune cursor for hand-written lexers and tokenizers:
// a position/line/column-tracking scanner over an in-memory string with a rich
// consume/match surface (consume-until, match-prefix, mark/rewind, indexed
// lookahead). It is the general core extracted from a faithful port of jsoup's
// org.jsoup.parser.CharacterReader (jsoup-1.22.2) — every CONSUME/MATCH semantic
// is preserved, with the HTML-token-specific consumers left to the caller.
//
// The whole input is buffered as one []rune at construction and never refilled;
// the streaming-refill fields (consumed / bufLength) are retained so that
// Pos()/ConsumeToEnd()/the sequence-straddling branch of ConsumeToSeq read
// identically to the original streaming implementation. Because the buffer never
// shifts, consumed stays 0 and bufLength stays len(charBuf).
//
// A Reader is not safe for concurrent use.

// EOF is the sentinel returned by Current/Consume at end of input — jsoup's
// `(char) -1`, an unsigned 16-bit char (0xFFFF), so it can never collide with a
// real input rune from a UTF-16-derived source.
const EOF rune = 0xFFFF

const maxStringCacheLen = 12
const stringCacheSize = 512

// BufferSize / RefillPoint mirror the streaming constants of the original reader.
// BufferSize is exported because conformance tests reference it.
const BufferSize = 1024 * 2
const RefillPoint = BufferSize / 2
const rewindLimit = 1024

// Reader is a rune-buffer cursor. Input char[] (UTF-16) becomes []rune so the
// char semantics of ported conformance inputs match exactly.
type Reader struct {
	charBuf   []rune // character buffer we consume from
	bufPos    int    // position in charBuf that's been consumed to
	bufLength int    // number of characters buffered in charBuf
	consumed  int    // total consumed less current bufPos (always 0 whole-buffer)
	bufMark   int    // if not -1, the marked rewind position

	stringCache []string // reused strings in this scan, to lessen garbage

	newlinesTracked  bool  // newlinePositions != nil is the underlying flag
	newlinePositions []int // pos() of newlines, tracked during scan
	lineNumberOffset int   // line numbers start at 1

	lastIcSeq    string // scan cache for ContainsIgnoreCase
	lastIcSeqSet bool
	lastIcIndex  int // nearest found indexOf
}

// New constructs a Reader over the whole input string.
func New(input string) *Reader {
	r := &Reader{
		charBuf:          []rune(input),
		bufMark:          -1,
		stringCache:      make([]string, stringCacheSize),
		lineNumberOffset: 1,
	}
	r.bufLength = len(r.charBuf)
	return r
}

// Close releases references so the buffer can be collected.
func (r *Reader) Close() {
	r.charBuf = nil
	r.stringCache = nil
}

// bufferUp is a no-op in the whole-buffer model: the input is fully buffered at
// construction and never refilled. Kept because the ported algorithms call it.
func (r *Reader) bufferUp() {}

// Mark records the current position so it can be rewound to.
func (r *Reader) Mark() {
	r.bufferUp()
	r.bufMark = r.bufPos
}

// Unmark clears the mark.
func (r *Reader) Unmark() {
	r.bufMark = -1
}

// RewindToMark restores the position to the mark. Panics if not marked.
func (r *Reader) RewindToMark() {
	if r.bufMark == -1 {
		panic("scan: Mark invalid")
	}
	r.bufPos = r.bufMark
	r.Unmark()
}

// Pos gets the position currently read to. Starts at 0.
func (r *Reader) Pos() int {
	return r.consumed + r.bufPos
}

// ReadFully reports whether the buffer has been fully read. Always true in the
// whole-buffer model (retained for parity with the streaming interface).
func (r *Reader) ReadFully() bool {
	return true
}

// TrackNewlines enables or disables line-number tracking. Off by default.
func (r *Reader) TrackNewlines(track bool) {
	if track && !r.newlinesTracked {
		r.newlinesTracked = true
		r.newlinePositions = make([]int, 0, BufferSize/80)
		r.scanBufferForNewlines()
	} else if !track {
		r.newlinesTracked = false
		r.newlinePositions = nil
	}
}

// IsTrackNewlines reports whether newline tracking is enabled.
func (r *Reader) IsTrackNewlines() bool {
	return r.newlinesTracked
}

// LineNumber gets the current line number (consumed to). Starts at 1.
func (r *Reader) LineNumber() int {
	return r.LineNumberAt(r.Pos())
}

// LineNumberAt gets the line number at a given position. Starts at 1.
func (r *Reader) LineNumberAt(pos int) int {
	if !r.IsTrackNewlines() {
		return 1
	}
	i := r.lineNumIndex(pos)
	if i == -1 {
		return r.lineNumberOffset
	}
	return i + r.lineNumberOffset + 1
}

// ColumnNumber gets the current column number (consumed to). Starts at 1.
func (r *Reader) ColumnNumber() int {
	return r.ColumnNumberAt(r.Pos())
}

// ColumnNumberAt gets the column number at a given position. Starts at 1.
func (r *Reader) ColumnNumberAt(pos int) int {
	if !r.IsTrackNewlines() {
		return pos + 1
	}
	i := r.lineNumIndex(pos)
	if i == -1 {
		return pos + 1
	}
	return pos - r.newlinePositions[i] + 1
}

// PosLineCol formats the current line and column as "line:col".
func (r *Reader) PosLineCol() string {
	return itoa(r.LineNumber()) + ":" + itoa(r.ColumnNumber())
}

func (r *Reader) lineNumIndex(pos int) int {
	if !r.IsTrackNewlines() {
		return 0
	}
	i := binarySearchInts(r.newlinePositions, pos)
	if i < -1 {
		i = abs(i) - 2
	}
	return i
}

// scanBufferForNewlines records newline positions for line-number tracking.
func (r *Reader) scanBufferForNewlines() {
	if !r.IsTrackNewlines() {
		return
	}
	if len(r.newlinePositions) > 0 {
		// work out the line number read up to (only fires on refills, which do
		// not occur in the whole-buffer model — kept for fidelity).
		index := r.lineNumIndex(r.consumed)
		if index == -1 {
			index = 0
		}
		linePos := r.newlinePositions[index]
		r.lineNumberOffset += index
		r.newlinePositions = r.newlinePositions[:0]
		r.newlinePositions = append(r.newlinePositions, linePos)
	}
	for i := r.bufPos; i < r.bufLength; i++ {
		if r.charBuf[i] == '\n' {
			r.newlinePositions = append(r.newlinePositions, 1+r.consumed+i)
		}
	}
}

// IsEmpty reports whether all the content has been read.
func (r *Reader) IsEmpty() bool {
	r.bufferUp()
	return r.bufPos >= r.bufLength
}

func (r *Reader) isEmptyNoBufferUp() bool {
	return r.bufPos >= r.bufLength
}

// Current gets the char at the current position (EOF if empty).
func (r *Reader) Current() rune {
	r.bufferUp()
	if r.isEmptyNoBufferUp() {
		return EOF
	}
	return r.charBuf[r.bufPos]
}

// Consume takes one character off the queue (EOF if empty). Advances even at
// end of input.
func (r *Reader) Consume() rune {
	r.bufferUp()
	val := EOF
	if !r.isEmptyNoBufferUp() {
		val = r.charBuf[r.bufPos]
	}
	r.bufPos++
	return val
}

// Unconsume steps back one character. MUST only be called directly after a
// Consume. Panics if there is nothing to unconsume.
func (r *Reader) Unconsume() {
	if r.bufPos < 1 {
		panic("scan: no buffer left to unconsume")
	}
	r.bufPos--
}

// Advance moves the current position by one.
func (r *Reader) Advance() {
	r.bufPos++
}

// NextIndexOf returns the offset from the current position to the next instance
// of c, or -1 if not found.
func (r *Reader) NextIndexOf(c rune) int {
	r.bufferUp()
	for i := r.bufPos; i < r.bufLength; i++ {
		if c == r.charBuf[i] {
			return i - r.bufPos
		}
	}
	return -1
}

// NextIndexOfSeq returns the offset from the current position to the next
// instance of seq, or -1 if not found.
func (r *Reader) NextIndexOfSeq(seq string) int {
	r.bufferUp()
	sq := []rune(seq)
	startChar := sq[0]
	for offset := r.bufPos; offset < r.bufLength; offset++ {
		// scan to first instance of startChar:
		if startChar != r.charBuf[offset] {
			for {
				offset++
				if !(offset < r.bufLength && startChar != r.charBuf[offset]) {
					break
				}
			}
		}
		i := offset + 1
		last := i + len(sq) - 1
		if offset < r.bufLength && last <= r.bufLength {
			for j := 1; i < last && sq[j] == r.charBuf[i]; i, j = i+1, j+1 {
			}
			if i == last {
				return offset - r.bufPos
			}
		}
	}
	return -1
}

// ConsumeTo reads characters up to (but not including) the delimiter char.
func (r *Reader) ConsumeTo(c rune) string {
	offset := r.NextIndexOf(c)
	if offset != -1 {
		consumed := cacheString(r.charBuf, r.stringCache, r.bufPos, offset)
		r.bufPos += offset
		return consumed
	}
	return r.ConsumeToEnd()
}

// ConsumeToSeq reads characters up to (but not including) the case-sensitive
// string. If not found in the buffer, returns the remainder less the sequence
// length so the call may be repeated (buffer-straddling behaviour).
func (r *Reader) ConsumeToSeq(seq string) string {
	offset := r.NextIndexOfSeq(seq)
	seqLen := len([]rune(seq))
	if offset != -1 {
		consumed := cacheString(r.charBuf, r.stringCache, r.bufPos, offset)
		r.bufPos += offset
		return consumed
	} else if r.bufLength-r.bufPos < seqLen {
		return r.ConsumeToEnd()
	}
	endPos := r.bufLength - seqLen + 1
	consumed := cacheString(r.charBuf, r.stringCache, r.bufPos, endPos-r.bufPos)
	r.bufPos = endPos
	return consumed
}

// consumeMatching reads characters while fn returns true, up to maxLength
// (-1 = no maximum).
func (r *Reader) consumeMatching(fn func(rune) bool, maxLength int) string {
	r.bufferUp()
	pos := r.bufPos
	start := pos
	remaining := r.bufLength
	val := r.charBuf
	for pos < remaining && (maxLength == -1 || pos-start < maxLength) && fn(val[pos]) {
		pos++
	}
	r.bufPos = pos
	if pos > start {
		return cacheString(r.charBuf, r.stringCache, start, pos-start)
	}
	return ""
}

// ConsumeMatching reads characters while fn returns true, and returns them. It is
// the building block for domain-specific consumers (consume a tag name, an
// attribute value, a token body): pass the predicate that defines the run.
func (r *Reader) ConsumeMatching(fn func(rune) bool) string {
	return r.consumeMatching(fn, -1)
}

// ConsumeToAny reads characters until the first of any delimiters is found.
func (r *Reader) ConsumeToAny(chars ...rune) string {
	return r.consumeMatching(func(c rune) bool {
		for _, seek := range chars {
			if c == seek {
				return false
			}
		}
		return true
	}, -1)
}

// ConsumeToAnySorted reads characters until a char from the sorted set is found.
func (r *Reader) ConsumeToAnySorted(chars ...rune) string {
	return r.consumeMatching(func(c rune) bool {
		return binarySearchRunes(chars, c) < 0
	}, -1)
}

// ConsumeToEnd consumes the remaining buffer.
func (r *Reader) ConsumeToEnd() string {
	r.bufferUp()
	data := cacheString(r.charBuf, r.stringCache, r.bufPos, r.bufLength-r.bufPos)
	r.bufPos = r.bufLength
	return data
}

// ConsumeLetterSequence consumes a run of Unicode letters.
func (r *Reader) ConsumeLetterSequence() string {
	return r.consumeMatching(func(c rune) bool {
		return unicode.IsLetter(c)
	}, -1)
}

// ConsumeLetterThenDigitSequence consumes ASCII letters then ASCII digits.
func (r *Reader) ConsumeLetterThenDigitSequence() string {
	r.bufferUp()
	start := r.bufPos
	for r.bufPos < r.bufLength {
		if isAsciiLetter(r.charBuf[r.bufPos]) {
			r.bufPos++
		} else {
			break
		}
	}
	for !r.isEmptyNoBufferUp() {
		if isDigit(r.charBuf[r.bufPos]) {
			r.bufPos++
		} else {
			break
		}
	}
	return cacheString(r.charBuf, r.stringCache, start, r.bufPos-start)
}

// ConsumeHexSequence consumes a run of hex digits.
func (r *Reader) ConsumeHexSequence() string {
	return r.consumeMatching(isHexDigit, -1)
}

// ConsumeDigitSequence consumes a run of ASCII digits.
func (r *Reader) ConsumeDigitSequence() string {
	return r.consumeMatching(func(c rune) bool {
		return c >= '0' && c <= '9'
	}, -1)
}

// Matches reports whether the current char equals c.
func (r *Reader) Matches(c rune) bool {
	return !r.IsEmpty() && r.charBuf[r.bufPos] == c
}

// MatchesSeq reports whether the buffer at the current position starts with seq
// (case sensitive).
func (r *Reader) MatchesSeq(seq string) bool {
	r.bufferUp()
	sq := []rune(seq)
	scanLength := len(sq)
	if scanLength > r.bufLength-r.bufPos {
		return false
	}
	for offset := 0; offset < scanLength; offset++ {
		if sq[offset] != r.charBuf[r.bufPos+offset] {
			return false
		}
	}
	return true
}

// MatchesIgnoreCase reports whether the buffer starts with seq, case insensitively.
func (r *Reader) MatchesIgnoreCase(seq string) bool {
	r.bufferUp()
	sq := []rune(seq)
	scanLength := len(sq)
	if scanLength > r.bufLength-r.bufPos {
		return false
	}
	for offset := 0; offset < scanLength; offset++ {
		scan := sq[offset]
		target := r.charBuf[r.bufPos+offset]
		if scan == target {
			continue
		}
		scan = unicode.ToUpper(scan)
		target = unicode.ToUpper(target)
		if scan != target {
			return false
		}
	}
	return true
}

// MatchesAny reports whether the next char matches any of seq, case sensitively.
func (r *Reader) MatchesAny(seq ...rune) bool {
	if r.IsEmpty() {
		return false
	}
	r.bufferUp()
	c := r.charBuf[r.bufPos]
	for _, seek := range seq {
		if seek == c {
			return true
		}
	}
	return false
}

// MatchesAnySorted reports whether the next char is in the sorted set.
func (r *Reader) MatchesAnySorted(seq []rune) bool {
	r.bufferUp()
	return !r.IsEmpty() && binarySearchRunes(seq, r.charBuf[r.bufPos]) >= 0
}

// MatchesAsciiAlpha reports whether the current char is an ASCII letter.
func (r *Reader) MatchesAsciiAlpha() bool {
	if r.IsEmpty() {
		return false
	}
	return isAsciiLetter(r.charBuf[r.bufPos])
}

// MatchesDigit reports whether the current char is an ASCII digit.
func (r *Reader) MatchesDigit() bool {
	if r.IsEmpty() {
		return false
	}
	return isDigit(r.charBuf[r.bufPos])
}

// MatchConsume consumes seq if it matches at the current position.
func (r *Reader) MatchConsume(seq string) bool {
	r.bufferUp()
	if r.MatchesSeq(seq) {
		r.bufPos += len([]rune(seq))
		return true
	}
	return false
}

// MatchConsumeIgnoreCase consumes seq (case insensitive) if it matches.
func (r *Reader) MatchConsumeIgnoreCase(seq string) bool {
	if r.MatchesIgnoreCase(seq) {
		r.bufPos += len([]rune(seq))
		return true
	}
	return false
}

// ContainsIgnoreCase checks presence of seq ahead in the buffer, but only finds
// consistent case (all-lower or all-upper) — the fast path a raw-text scan needs.
func (r *Reader) ContainsIgnoreCase(seq string) bool {
	if r.lastIcSeqSet && seq == r.lastIcSeq {
		if r.lastIcIndex == -1 {
			return false
		}
		if r.lastIcIndex >= r.bufPos {
			return true
		}
	}
	r.lastIcSeq = seq
	r.lastIcSeqSet = true

	loScan := strings.ToLower(seq)
	lo := r.NextIndexOfSeq(loScan)
	if lo > -1 {
		r.lastIcIndex = r.bufPos + lo
		return true
	}

	hiScan := strings.ToUpper(seq)
	hi := r.NextIndexOfSeq(hiScan)
	found := hi > -1
	if found {
		r.lastIcIndex = r.bufPos + hi
	} else {
		r.lastIcIndex = -1
	}
	return found
}

// String returns the unconsumed remainder of the buffer.
func (r *Reader) String() string {
	if r.bufLength-r.bufPos < 0 {
		return ""
	}
	return string(r.charBuf[r.bufPos:r.bufLength])
}

// RangeEquals reports whether the buffer range equals cached. Useful in tests.
func (r *Reader) RangeEquals(start, count int, cached string) bool {
	return rangeEqualsBuf(r.charBuf, start, count, cached)
}

// cacheString caches short strings as a flyweight to reduce garbage. On hash
// collision it falls back to a fresh string.
func cacheString(charBuf []rune, stringCache []string, start, count int) string {
	if count > maxStringCacheLen {
		return string(charBuf[start : start+count])
	}
	if count < 1 {
		return ""
	}

	// calculate hash (32-bit overflow semantics):
	var hash int32 = 0
	end := count + start
	for i := start; i < end; i++ {
		hash = 31*hash + int32(charBuf[i])
	}

	index := int(hash) & (stringCacheSize - 1)
	cached := stringCache[index]

	if cached != "" && rangeEqualsBuf(charBuf, start, count, cached) {
		return cached
	}
	built := string(charBuf[start : start+count])
	stringCache[index] = built
	return built
}

// rangeEqualsBuf reports whether the buffer range equals cached.
func rangeEqualsBuf(charBuf []rune, start, count int, cached string) bool {
	cr := []rune(cached)
	if count == len(cr) {
		i := start
		j := 0
		for count != 0 {
			count--
			if charBuf[i] != cr[j] {
				return false
			}
			i++
			j++
		}
		return true
	}
	return false
}

// --- small helpers ---

func isAsciiLetter(c rune) bool {
	return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z')
}

func isDigit(c rune) bool {
	return c >= '0' && c <= '9'
}

func isHexDigit(c rune) bool {
	return isDigit(c) || (c >= 'A' && c <= 'F') || (c >= 'a' && c <= 'f')
}

func abs(i int) int {
	if i < 0 {
		return -i
	}
	return i
}

// binarySearchInts mirrors java.util.Collections.binarySearch: returns the index
// of key if present, else -(insertionPoint) - 1.
func binarySearchInts(a []int, key int) int {
	lo, hi := 0, len(a)-1
	for lo <= hi {
		mid := int(uint(lo+hi) >> 1)
		v := a[mid]
		if v < key {
			lo = mid + 1
		} else if v > key {
			hi = mid - 1
		} else {
			return mid
		}
	}
	return -(lo + 1)
}

// binarySearchRunes mirrors java.util.Arrays.binarySearch over a sorted rune set.
func binarySearchRunes(a []rune, key rune) int {
	lo, hi := 0, len(a)-1
	for lo <= hi {
		mid := int(uint(lo+hi) >> 1)
		v := a[mid]
		if v < key {
			lo = mid + 1
		} else if v > key {
			hi = mid - 1
		} else {
			return mid
		}
	}
	return -(lo + 1)
}

// itoa formats an int in base 10 (keeps strconv out of this package's surface).
func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	neg := n < 0
	if neg {
		n = -n
	}
	var b [20]byte
	i := len(b)
	for n > 0 {
		i--
		b[i] = byte('0' + n%10)
		n /= 10
	}
	if neg {
		i--
		b[i] = '-'
	}
	return string(b[i:])
}
