// Code generated by goplus from source.gp. DO NOT EDIT.
//goplus:v v0.28.0

// Capability-scoped source loading and watch/reload for config.
//
// The resolution core (config.gp) takes pre-materialized Layers; this file adds
// the missing half — LOADING a Layer from a backing (file, environment,
// directory) under an explicit effect permission, and detecting when a source
// has CHANGED so the snapshot can be reloaded. The effect of touching a source
// lives entirely behind Probe/Load: a caller stays pure until it presents a
// granting Capability.
package config

// Capability authorizes reading a source — the effect permission that gates a
// Load. Granted permits the read; Denied carries the reason and makes Load skip
// the source. This is where a consumer's access policy lives: a file-based
// loader grants when the file exists and is readable; a per-directory loader
// grants when the directory's config has been allowed and denies when blocked.
//
//goplus:enum Capability
type Capability interface{ isCapability() }

//goplus:variant (Capability) Granted()
type Granted struct{}

func (Granted) isCapability() {}

//goplus:variant (Capability) Denied(Reason string)
type Denied struct {
	Reason string
}

func (Denied) isCapability() {}

// CapabilityCases selects one handler per Capability variant for CapabilityFold.
type CapabilityCases[R any] struct {
	Granted func() R
	Denied  func(Reason string) R
}

// CapabilityFold reduces Capability by one-level case analysis.
func CapabilityFold[R any](v Capability, cs CapabilityCases[R]) R {
	switch m := any(v).(type) {
	case Granted:
		return cs.Granted()
	case Denied:
		return cs.Denied(m.Reason)
	default:
		panic("goplus: impossible enum value in CapabilityFold")
	}
}

// CapabilityEqOverrides carries optional per-variant hooks for CapabilityEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type CapabilityEqOverrides struct {
	Granted func(x, y Granted) (eq, handled bool)
	Denied  func(x, y Denied) (eq, handled bool)
}

// CapabilityEqualWith reports structural equality of a and b under ov.
func CapabilityEqualWith(a, b Capability, ov CapabilityEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case Granted:
		y, ok := any(b).(Granted)
		if !ok {
			return false
		}
		if ov.Granted != nil {
			if eq, handled := ov.Granted(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case Denied:
		y, ok := any(b).(Denied)
		if !ok {
			return false
		}
		if ov.Denied != nil {
			if eq, handled := ov.Denied(x, y); handled {
				return eq
			}
		}
		if x.Reason != y.Reason {
			return false
		}
		return true
	}
	return false
}

// CapabilityEqual reports structural equality of a and b.
func CapabilityEqual(a, b Capability) bool {
	return CapabilityEqualWith(a, b, CapabilityEqOverrides{})
}

// IsGranted reports whether a capability permits the load.
func IsGranted(c Capability) bool {
	switch any(c).(type) {
	case Granted:

		return true
	case Denied:

		return false
	default:
		panic("goplus: impossible enum value in match")
	}
}

// Fingerprint is a source's change-detection token: an opaque content/mtime
// token plus whether the source currently exists. Reload compares fingerprints;
// equal fingerprints mean the resolved snapshot is still current for that
// source.
type Fingerprint struct {
	Token  string
	Exists bool
}

// FingerprintEqual reports whether two fingerprints denote no change.
func FingerprintEqual(a, b Fingerprint) bool {
	return a.Exists == b.Exists && a.Token == b.Token
}

// Loaded is the outcome of a Load: the source either contributed a Layer or was
// Skipped (denied capability, or absent), always paired with the fingerprint
// observed at load time so the caller can seed a watch.
//
//goplus:enum Loaded
type Loaded interface{ isLoaded() }

//goplus:variant (Loaded) Skipped(Reason string, Fingerprint Fingerprint)
type Skipped struct {
	Reason      string
	Fingerprint Fingerprint
}

func (Skipped) isLoaded() {}

//goplus:variant (Loaded) Applied(Layer Layer, Fingerprint Fingerprint)
type Applied struct {
	Layer       Layer
	Fingerprint Fingerprint
}

func (Applied) isLoaded() {}

// LoadedCases selects one handler per Loaded variant for LoadedFold.
type LoadedCases[R any] struct {
	Skipped func(Reason string, Fingerprint Fingerprint) R
	Applied func(Layer Layer, Fingerprint Fingerprint) R
}

// LoadedFold reduces Loaded by one-level case analysis.
func LoadedFold[R any](l Loaded, cs LoadedCases[R]) R {
	switch m := any(l).(type) {
	case Skipped:
		return cs.Skipped(m.Reason, m.Fingerprint)
	case Applied:
		return cs.Applied(m.Layer, m.Fingerprint)
	default:
		panic("goplus: impossible enum value in LoadedFold")
	}
}

// Loader reads exactly one configuration source. Provenance fixes the Source
// (and thus the resolution precedence and each Entry's provenance). Probe
// returns the current fingerprint without materializing values (for watch);
// Load reads the values into a Layer, gated by a Capability.
type Loader interface {
	Provenance() Source
	Probe() (Fingerprint, error)
	Load(cap Capability) (Loaded, error)
}

// sourceName is the lowercase provenance label used in load-error field paths.
func sourceName(s Source) string {
	switch any(s).(type) {
	case DefaultSource:

		return "default"
	case RemoteSource:

		return "remote"
	case FileSource:

		return "file"
	case EnvironmentSource:

		return "environment"
	case FlagSource:

		return "flag"
	case OverrideSource:

		return "override"
	default:
		panic("goplus: impossible enum value in match")
	}
}

// LoadAll loads every loader in caller order, gating each with grant(source).
// It returns the produced layers (pass to Resolve), each source's fingerprint
// (seed a watch), and per-source load errors (path-tagged by provenance). A
// denied or absent source contributes no layer, so resolution falls back to
// lower-precedence values — capability-scoped loading is failure-tolerant by
// construction.
func LoadAll(grant func(Source) Capability, loaders ...Loader) (layers []Layer, prints map[Source]Fingerprint, errs []error) {
	prints = make(map[Source]Fingerprint)
	for _, loader := range loaders {
		source := loader.Provenance()
		loaded, err := loader.Load(grant(source))
		if err != nil {
			errs = append(errs, At(sourceName(source), err))
		}
		switch __gp_m2 := any(loaded).(type) {
		case Applied:
			layer := __gp_m2.Layer
			fp := __gp_m2.Fingerprint

			layers = append(layers, layer)
			prints[source] = fp
		case Skipped:
			fp := __gp_m2.Fingerprint

			prints[source] = fp
		default:
			panic("goplus: impossible enum value in match")
		}
	}
	return
}

// Reload re-probes every loader and reports which sources changed since prev.
// An empty changed set means the resolved snapshot is still valid; otherwise the
// caller re-runs LoadAll + Resolve for a fresh snapshot. This is the single
// watch/reload law shared by a filesystem notifier and an mtime ledger: a source
// reloads exactly when its fingerprint differs from the one last observed.
func Reload(prev map[Source]Fingerprint, loaders ...Loader) (changed []Source, now map[Source]Fingerprint, errs []error) {
	now = make(map[Source]Fingerprint)
	for _, loader := range loaders {
		source := loader.Provenance()
		fp, err := loader.Probe()
		if err != nil {
			errs = append(errs, At(sourceName(source), err))
			continue
		}
		now[source] = fp
		old, seen := prev[source]
		if !seen || !FingerprintEqual(old, fp) {
			changed = append(changed, source)
		}
	}
	return
}
