// Code generated by goplus from buffer.gp. DO NOT EDIT.
//goplus:v v0.28.0

package memory

import "goforge.dev/goplus/std/option"

type Buffer[T any] struct{ values []T }

func NewBuffer[T any](capacity int) Buffer[T] {
	if capacity < 0 {
		capacity = 0
	}
	return Buffer[T]{values: make([]T, 0, capacity)}
}
func (buffer Buffer[T]) Len() int        { return len(buffer.values) }
func (buffer Buffer[T]) Cap() int        { return cap(buffer.values) }
func (buffer *Buffer[T]) Append(value T) { buffer.values = append(buffer.values, value) }
func (buffer Buffer[T]) At(index int) option.Option[T] {
	if index < 0 || index >= len(buffer.values) {
		return option.None[T]{}
	}
	return option.Some[T]{Value: buffer.values[index]}
}
func (buffer *Buffer[T]) Set(index int, value T) bool {
	if index < 0 || index >= len(buffer.values) {
		return false
	}
	buffer.values[index] = value
	return true
}
func (buffer *Buffer[T]) Remove(index int) option.Option[T] {
	if index < 0 || index >= len(buffer.values) {
		return option.None[T]{}
	}
	removed := buffer.values[index]
	copy(buffer.values[index:], buffer.values[index+1:])
	var zero T
	buffer.values[len(buffer.values)-1] = zero
	buffer.values = buffer.values[:len(buffer.values)-1]
	return option.Some[T]{Value: removed}
}
func (buffer *Buffer[T]) Reset()   { clear(buffer.values); buffer.values = buffer.values[:0] }
func (buffer *Buffer[T]) Release() { clear(buffer.values); buffer.values = nil }
