// Code generated by goplus from buffer_test.gp. DO NOT EDIT.
//goplus:v v0.28.0

package memory

import (
	"testing"
	"testing/quick"

	"goforge.dev/goplus/std/option"
)

func TestBufferRemovalPreservesOrderProperty(t *testing.T) {
	law := func(values []int, raw uint8) bool {
		buffer := NewBuffer[int](len(values))
		for _, value := range values {
			buffer.Append(value)
		}
		if len(values) == 0 {
			switch any(buffer.Remove(0)).(type) {
			case option.None[int]:
				return true
			case option.Some[int]:
				return false
			default:
				panic("goplus: impossible enum value in match")
			}
		}
		index := int(raw) % len(values)
		switch __gp_m1 := any(buffer.Remove(index)).(type) {
		case option.None[int]:
			return false
		case option.Some[int]:
			removed := __gp_m1.Value
			if removed != values[index] || buffer.Len() != len(values)-1 {
				return false
			}
			for position := 0; position < buffer.Len(); position++ {
				expected := values[position]
				if position >= index {
					expected = values[position+1]
				}
				switch __gp_m2 := any(buffer.At(position)).(type) {
				case option.None[int]:
					return false
				case option.Some[int]:
					found := __gp_m2.Value
					if found != expected {
						return false
					}
				default:
					panic("goplus: impossible enum value in match")
				}
			}
			return true
		default:
			panic("goplus: impossible enum value in match")
		}
	}
	if err := quick.Check(law, nil); err != nil {
		t.Fatal(err)
	}
}

func TestBufferResetRetainsAndReleaseDropsCapacity(t *testing.T) {
	buffer := NewBuffer[*int](8)
	value := 1
	buffer.Append(&value)
	buffer.Reset()
	if buffer.Len() != 0 || buffer.Cap() < 8 {
		t.Fatalf("reset = %d/%d", buffer.Len(), buffer.Cap())
	}
	buffer.Release()
	if buffer.Len() != 0 || buffer.Cap() != 0 {
		t.Fatalf("release = %d/%d", buffer.Len(), buffer.Cap())
	}
}

func TestBufferTruncateClearsTailAndRejectsGrowth(t *testing.T) {
	buffer := NewBuffer[int](4)
	buffer.Append(1)
	buffer.Append(2)
	if !buffer.Truncate(1) || buffer.Len() != 1 {
		t.Fatalf("truncate = %d", buffer.Len())
	}
	if buffer.Truncate(2) {
		t.Fatal("truncate grew buffer")
	}
	switch __gp_m3 := any(buffer.At(0)).(type) {
	case option.None[int]:
		t.Fatal("prefix was removed")
	case option.Some[int]:
		value := __gp_m3.Value
		if value != 1 {
			t.Fatalf("prefix = %d", value)
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}
