// Code generated by goplus from group.gp. DO NOT EDIT.
//goplus:v v0.28.0

package memory

import (
	"sync"

	"goforge.dev/goplus/std/result"
)

type Group struct {
	mu       sync.Mutex
	arena    *Arena
	handles  []Handle
	released bool
}

func (arena *Arena) Group() result.Result[*Group, Failure] {
	if arena == nil {
		return result.Err[*Group, Failure]{Err: InvalidConfiguration{Message: "arena is nil"}}
	}
	stats := arena.Stats()
	if stats.Closed {
		return result.Err[*Group, Failure]{Err: ArenaClosed{}}
	}
	return result.Ok[*Group, Failure]{Value: &Group{arena: arena}}
}

func (group *Group) Allocate(size int, alignment int) result.Result[Handle, Failure] {
	group.mu.Lock()
	defer group.mu.Unlock()
	if group.released {
		return result.Err[Handle, Failure]{Err: GroupReleased{}}
	}
	switch __gp_m0 := any(group.arena.Allocate(size, alignment)).(type) {
	case result.Err[Handle, Failure]:
		failure := __gp_m0.Err
		return result.Err[Handle, Failure]{Err: failure}
	case result.Ok[Handle, Failure]:
		handle := __gp_m0.Value
		group.handles = append(group.handles, handle)
		return result.Ok[Handle, Failure]{Value: handle}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (group *Group) Reset() result.Result[Mutation, Failure] {
	group.mu.Lock()
	defer group.mu.Unlock()
	if group.released {
		return result.Err[Mutation, Failure]{Err: GroupReleased{}}
	}
	switch __gp_m1 := any(group.releaseHandles()).(type) {
	case result.Err[Mutation, Failure]:
		failure := __gp_m1.Err
		return result.Err[Mutation, Failure]{Err: failure}
	case result.Ok[Mutation, Failure]:
		group.handles = nil
		return result.Ok[Mutation, Failure]{Value: Applied{}}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (group *Group) Release() result.Result[Mutation, Failure] {
	group.mu.Lock()
	defer group.mu.Unlock()
	if group.released {
		return result.Ok[Mutation, Failure]{Value: Applied{}}
	}
	switch __gp_m2 := any(group.releaseHandles()).(type) {
	case result.Err[Mutation, Failure]:
		failure := __gp_m2.Err
		return result.Err[Mutation, Failure]{Err: failure}
	case result.Ok[Mutation, Failure]:
		group.handles = nil
		group.released = true
		return result.Ok[Mutation, Failure]{Value: Applied{}}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (group *Group) Stats() (Allocations int, Released bool) {
	group.mu.Lock()
	defer group.mu.Unlock()
	return len(group.handles), group.released
}

func (group *Group) releaseHandles() result.Result[Mutation, Failure] {
	for index := len(group.handles) - 1; index >= 0; index-- {
		switch __gp_m3 := any(group.arena.Delete(group.handles[index])).(type) {
		case result.Err[Mutation, Failure]:
			failure := __gp_m3.Err
			return result.Err[Mutation, Failure]{Err: failure}
		case result.Ok[Mutation, Failure]:
		default:
			panic("goplus: impossible enum value in match")
		}
	}
	return result.Ok[Mutation, Failure]{Value: Applied{}}
}
