// Code generated by goplus from group_layout_test.gp. DO NOT EDIT.
//goplus:v v0.28.0

package memory

import (
	"reflect"
	"testing"
	"testing/quick"

	"goforge.dev/goplus/std/result"
)

func TestGroupResetReclaimsAndReusesMembers(t *testing.T) {
	arena := requireArena(t)
	defer arena.Close()
	var group *Group
	switch __gp_m0 := any(arena.Group()).(type) {
	case result.Err[*Group, Failure]:
		failure := __gp_m0.Err
		t.Fatal(failure)
	case result.Ok[*Group, Failure]:
		created := __gp_m0.Value
		group = created
	default:
		panic("goplus: impossible enum value in match")
	}
	first := requireGroupAllocation(t, group, 32, 8)
	requireGroupAllocation(t, group, 16, 8)
	switch __gp_m1 := any(group.Reset()).(type) {
	case result.Err[Mutation, Failure]:
		failure := __gp_m1.Err
		t.Fatal(failure)
	case result.Ok[Mutation, Failure]:
	default:
		panic("goplus: impossible enum value in match")
	}
	if arena.Stats().Used != 0 {
		t.Fatalf("used = %d", arena.Stats().Used)
	}
	fresh := requireGroupAllocation(t, group, 32, 8)
	if first.offset != fresh.offset {
		t.Fatalf("offset = %d; want %d", fresh.offset, first.offset)
	}
	switch __gp_m2 := any(arena.Bytes(first)).(type) {
	case result.Ok[[]byte, Failure]:
		t.Fatal("group reset revived old handle")
	case result.Err[[]byte, Failure]:
		failure := __gp_m2.Err
		switch any(failure).(type) {
		case InvalidHandle:
		default:
			t.Fatal(failure)
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func TestReleasedGroupRejectsAllocation(t *testing.T) {
	arena := requireArena(t)
	defer arena.Close()
	var group *Group
	switch __gp_m4 := any(arena.Group()).(type) {
	case result.Err[*Group, Failure]:
		failure := __gp_m4.Err
		t.Fatal(failure)
	case result.Ok[*Group, Failure]:
		created := __gp_m4.Value
		group = created
	default:
		panic("goplus: impossible enum value in match")
	}
	switch __gp_m5 := any(group.Release()).(type) {
	case result.Err[Mutation, Failure]:
		failure := __gp_m5.Err
		t.Fatal(failure)
	case result.Ok[Mutation, Failure]:
	default:
		panic("goplus: impossible enum value in match")
	}
	switch __gp_m6 := any(group.Allocate(1, 1)).(type) {
	case result.Err[Handle, Failure]:
		failure := __gp_m6.Err
		switch any(failure).(type) {
		case GroupReleased:
		default:
			t.Fatal(failure)
		}
	case result.Ok[Handle, Failure]:
		t.Fatal("released group allocated")
	default:
		panic("goplus: impossible enum value in match")
	}
}

func TestSoARoundTripProperty(t *testing.T) {
	law := func(values []int16) bool {
		rows := make([]Row3[int16, int, bool], len(values))
		for index, value := range values {
			rows[index] = Row3[int16, int, bool]{First: value, Second: index, Third: index%2 == 0}
		}
		columns := FromRows3(rows)
		return reflect.DeepEqual(columns.Rows(), rows)
	}
	if err := quick.Check(law, nil); err != nil {
		t.Fatal(err)
	}
}

func TestSoAResetRetainsCapacityAndErasesLength(t *testing.T) {
	columns := NewSoA2[int, string](8)
	columns.Append(1, "secret")
	columns.Reset()
	if columns.Len() != 0 || cap(columns.first) < 8 || cap(columns.second) < 8 {
		t.Fatalf("reset = %d/%d/%d", columns.Len(), cap(columns.first), cap(columns.second))
	}
}

func requireGroupAllocation(t *testing.T, group *Group, size int, alignment int) Handle {
	switch __gp_m8 := any(group.Allocate(size, alignment)).(type) {
	case result.Ok[Handle, Failure]:
		handle := __gp_m8.Value
		return handle
	case result.Err[Handle, Failure]:
		failure := __gp_m8.Err
		t.Fatal(failure)
		return Handle{}
	default:
		panic("goplus: impossible enum value in match")
	}
}
