// Code generated by goplus from memory.gp. DO NOT EDIT.
//goplus:v v0.28.0

// Package memory provides explicit region lifetime, ownership, clearing, and
// reuse. Its primary Go+ API is algebraic: expected failures travel on Result,
// optional free-span locations travel on Option, and policy/state alternatives
// are exhaustive enums.
package memory

import (
	_ "fmt"
	"sync"
	"sync/atomic"

	"goforge.dev/goplus/std/option"
	"goforge.dev/goplus/std/result"
)

//goplus:enum ZeroPolicy
type ZeroPolicy interface{ isZeroPolicy() }

// ZeroOnRelease is the secure default and the zero value after erasure.
//
//goplus:variant (ZeroPolicy) ZeroOnRelease()
type ZeroOnRelease struct{}

func (ZeroOnRelease) isZeroPolicy() {}

// PreserveOnRelease is an explicit performance capability. Its caller must
// prove released bytes are neither secret nor observable before overwrite.
//
//goplus:variant (ZeroPolicy) PreserveOnRelease()
type PreserveOnRelease struct{}

func (PreserveOnRelease) isZeroPolicy() {}

// ZeroPolicyCases selects one handler per ZeroPolicy variant for ZeroPolicyFold.
type ZeroPolicyCases[R any] struct {
	ZeroOnRelease     func() R
	PreserveOnRelease func() R
}

// ZeroPolicyFold reduces ZeroPolicy by one-level case analysis.
func ZeroPolicyFold[R any](z ZeroPolicy, cs ZeroPolicyCases[R]) R {
	switch any(z).(type) {
	case ZeroOnRelease:
		return cs.ZeroOnRelease()
	case PreserveOnRelease:
		return cs.PreserveOnRelease()
	default:
		panic("goplus: impossible enum value in ZeroPolicyFold")
	}
}

// ZeroPolicyEqOverrides carries optional per-variant hooks for ZeroPolicyEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type ZeroPolicyEqOverrides struct {
	ZeroOnRelease     func(x, y ZeroOnRelease) (eq, handled bool)
	PreserveOnRelease func(x, y PreserveOnRelease) (eq, handled bool)
}

// ZeroPolicyEqualWith reports structural equality of a and b under ov.
func ZeroPolicyEqualWith(a, b ZeroPolicy, ov ZeroPolicyEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case ZeroOnRelease:
		y, ok := any(b).(ZeroOnRelease)
		if !ok {
			return false
		}
		if ov.ZeroOnRelease != nil {
			if eq, handled := ov.ZeroOnRelease(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case PreserveOnRelease:
		y, ok := any(b).(PreserveOnRelease)
		if !ok {
			return false
		}
		if ov.PreserveOnRelease != nil {
			if eq, handled := ov.PreserveOnRelease(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// ZeroPolicyEqual reports structural equality of a and b.
func ZeroPolicyEqual(a, b ZeroPolicy) bool {
	return ZeroPolicyEqualWith(a, b, ZeroPolicyEqOverrides{})
}

//goplus:enum Failure
type Failure interface{ isFailure() }

//goplus:variant (Failure) ArenaClosed()
type ArenaClosed struct{}

func (ArenaClosed) isFailure() {}

//goplus:variant (Failure) CapacityExhausted()
type CapacityExhausted struct{}

func (CapacityExhausted) isFailure() {}

//goplus:variant (Failure) InvalidHandle()
type InvalidHandle struct{}

func (InvalidHandle) isFailure() {}

//goplus:variant (Failure) InvalidCheckpoint()
type InvalidCheckpoint struct{}

func (InvalidCheckpoint) isFailure() {}

//goplus:variant (Failure) InvalidConfiguration(Message string)
type InvalidConfiguration struct {
	Message string
}

func (InvalidConfiguration) isFailure() {}

//goplus:variant (Failure) BoundsViolation(Operation string)
type BoundsViolation struct {
	Operation string
}

func (BoundsViolation) isFailure() {}

//goplus:variant (Failure) PlatformFailure(Cause error)
type PlatformFailure struct {
	Cause error
}

func (PlatformFailure) isFailure() {}

//goplus:variant (Failure) GroupReleased()
type GroupReleased struct{}

func (GroupReleased) isFailure() {}

// FailureCases selects one handler per Failure variant for FailureFold.
type FailureCases[R any] struct {
	ArenaClosed          func() R
	CapacityExhausted    func() R
	InvalidHandle        func() R
	InvalidCheckpoint    func() R
	InvalidConfiguration func(Message string) R
	BoundsViolation      func(Operation string) R
	PlatformFailure      func(Cause error) R
	GroupReleased        func() R
}

// FailureFold reduces Failure by one-level case analysis.
func FailureFold[R any](f Failure, cs FailureCases[R]) R {
	switch m := any(f).(type) {
	case ArenaClosed:
		return cs.ArenaClosed()
	case CapacityExhausted:
		return cs.CapacityExhausted()
	case InvalidHandle:
		return cs.InvalidHandle()
	case InvalidCheckpoint:
		return cs.InvalidCheckpoint()
	case InvalidConfiguration:
		return cs.InvalidConfiguration(m.Message)
	case BoundsViolation:
		return cs.BoundsViolation(m.Operation)
	case PlatformFailure:
		return cs.PlatformFailure(m.Cause)
	case GroupReleased:
		return cs.GroupReleased()
	default:
		panic("goplus: impossible enum value in FailureFold")
	}
}

// FailureEqOverrides carries optional per-variant hooks for FailureEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type FailureEqOverrides struct {
	ArenaClosed          func(x, y ArenaClosed) (eq, handled bool)
	CapacityExhausted    func(x, y CapacityExhausted) (eq, handled bool)
	InvalidHandle        func(x, y InvalidHandle) (eq, handled bool)
	InvalidCheckpoint    func(x, y InvalidCheckpoint) (eq, handled bool)
	InvalidConfiguration func(x, y InvalidConfiguration) (eq, handled bool)
	BoundsViolation      func(x, y BoundsViolation) (eq, handled bool)
	PlatformFailure      func(x, y PlatformFailure) (eq, handled bool)
	GroupReleased        func(x, y GroupReleased) (eq, handled bool)
}

// FailureEqualWith reports structural equality of a and b under ov.
func FailureEqualWith(a, b Failure, ov FailureEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case ArenaClosed:
		y, ok := any(b).(ArenaClosed)
		if !ok {
			return false
		}
		if ov.ArenaClosed != nil {
			if eq, handled := ov.ArenaClosed(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case CapacityExhausted:
		y, ok := any(b).(CapacityExhausted)
		if !ok {
			return false
		}
		if ov.CapacityExhausted != nil {
			if eq, handled := ov.CapacityExhausted(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case InvalidHandle:
		y, ok := any(b).(InvalidHandle)
		if !ok {
			return false
		}
		if ov.InvalidHandle != nil {
			if eq, handled := ov.InvalidHandle(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case InvalidCheckpoint:
		y, ok := any(b).(InvalidCheckpoint)
		if !ok {
			return false
		}
		if ov.InvalidCheckpoint != nil {
			if eq, handled := ov.InvalidCheckpoint(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case InvalidConfiguration:
		y, ok := any(b).(InvalidConfiguration)
		if !ok {
			return false
		}
		if ov.InvalidConfiguration != nil {
			if eq, handled := ov.InvalidConfiguration(x, y); handled {
				return eq
			}
		}
		if x.Message != y.Message {
			return false
		}
		return true
	case BoundsViolation:
		y, ok := any(b).(BoundsViolation)
		if !ok {
			return false
		}
		if ov.BoundsViolation != nil {
			if eq, handled := ov.BoundsViolation(x, y); handled {
				return eq
			}
		}
		if x.Operation != y.Operation {
			return false
		}
		return true
	case PlatformFailure:
		y, ok := any(b).(PlatformFailure)
		if !ok {
			return false
		}
		if ov.PlatformFailure != nil {
			if eq, handled := ov.PlatformFailure(x, y); handled {
				return eq
			}
		}
		if (x.Cause == nil) != (y.Cause == nil) {
			return false
		}
		if x.Cause != nil && x.Cause.Error() != y.Cause.Error() {
			return false
		}
		return true
	case GroupReleased:
		y, ok := any(b).(GroupReleased)
		if !ok {
			return false
		}
		if ov.GroupReleased != nil {
			if eq, handled := ov.GroupReleased(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// FailureEqual reports structural equality of a and b.
func FailureEqual(a, b Failure) bool {
	return FailureEqualWith(a, b, FailureEqOverrides{})
}

//goplus:method (Failure) Error
func Error(failure Failure) string {
	switch __gp_m0 := any(failure).(type) {
	case ArenaClosed:

		return "memory: arena is closed"
	case CapacityExhausted:

		return "memory: arena capacity exhausted"
	case InvalidHandle:

		return "memory: invalid or expired handle"
	case InvalidCheckpoint:

		return "memory: checkpoint does not belong to this arena generation"
	case InvalidConfiguration:
		message := __gp_m0.Message

		return "memory: " + message
	case BoundsViolation:
		operation := __gp_m0.Operation

		return "memory: " + operation + " exceeds allocation bounds"
	case PlatformFailure:
		cause := __gp_m0.Cause

		return "memory: platform storage: " + cause.Error()
	case GroupReleased:

		return "memory: allocation group is released"
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:method (Failure) Unwrap
func Unwrap(failure Failure) error {
	switch __gp_m1 := any(failure).(type) {
	case PlatformFailure:
		cause := __gp_m1.Cause

		return cause
	default:

		return nil
	}
}

//goplus:enum Mutation
type Mutation interface{ isMutation() }

//goplus:variant (Mutation) Applied()
type Applied struct{}

func (Applied) isMutation() {}

// MutationCases selects one handler per Mutation variant for MutationFold.
type MutationCases[R any] struct {
	Applied func() R
}

// MutationFold reduces Mutation by one-level case analysis.
func MutationFold[R any](m Mutation, cs MutationCases[R]) R {
	switch any(m).(type) {
	case Applied:
		return cs.Applied()
	default:
		panic("goplus: impossible enum value in MutationFold")
	}
}

// MutationEqOverrides carries optional per-variant hooks for MutationEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type MutationEqOverrides struct {
	Applied func(x, y Applied) (eq, handled bool)
}

// MutationEqualWith reports structural equality of a and b under ov.
func MutationEqualWith(a, b Mutation, ov MutationEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case Applied:
		y, ok := any(b).(Applied)
		if !ok {
			return false
		}
		if ov.Applied != nil {
			if eq, handled := ov.Applied(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// MutationEqual reports structural equality of a and b.
func MutationEqual(a, b Mutation) bool {
	return MutationEqualWith(a, b, MutationEqOverrides{})
}

type Config struct {
	Capacity int
	Zero     ZeroPolicy
}

type Handle struct {
	id         uint64
	offset     int
	length     int
	generation uint64
}

func (handle Handle) Len() int     { return handle.length }
func (handle Handle) IsZero() bool { return handle.id == 0 }

type Checkpoint struct {
	arena      uint64
	generation uint64
	order      int
}

type Stats struct {
	Capacity    int
	Used        int
	Peak        int
	Allocations int
	Generation  uint64
	Closed      bool
}

type allocation struct {
	offset int
	length int
	alive  bool
}

type span struct {
	offset int
	length int
}

type Arena struct {
	mu          sync.Mutex
	id          uint64
	storage     []byte
	cursor      int
	free        []span
	allocations map[uint64]allocation
	order       []uint64
	nextID      uint64
	generation  uint64
	used        int
	peak        int
	zero        ZeroPolicy
	closed      bool
}

var nextArenaID atomic.Uint64

func New(config Config) result.Result[*Arena, Failure] {
	if config.Capacity <= 0 {
		return result.Err[*Arena, Failure]{Err: InvalidConfiguration{Message: "capacity must be positive"}}
	}
	switch __gp_m2 := any(result.Of(platformAllocate(config.Capacity))).(type) {
	case result.Ok[[]byte, error]:
		storage := __gp_m2.Value

		return result.Ok[*Arena, Failure]{Value: &Arena{
			id:          nextArenaID.Add(1),
			storage:     storage,
			allocations: map[uint64]allocation{},
			nextID:      1,
			generation:  1,
			zero:        config.Zero,
		}}
	case result.Err[[]byte, error]:
		cause := __gp_m2.Err

		return result.Err[*Arena, Failure]{Err: PlatformFailure{Cause: cause}}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (arena *Arena) Allocate(size int, alignment int) result.Result[Handle, Failure] {
	arena.mu.Lock()
	defer arena.mu.Unlock()
	if arena.closed {
		return result.Err[Handle, Failure]{Err: ArenaClosed{}}
	}
	if size < 0 {
		return result.Err[Handle, Failure]{Err: InvalidConfiguration{Message: "allocation size cannot be negative"}}
	}
	if alignment <= 0 || alignment&(alignment-1) != 0 {
		return result.Err[Handle, Failure]{Err: InvalidConfiguration{Message: "alignment must be a positive power of two"}}
	}
	if size == 0 {
		size = 1
	}
	offset := 0
	switch __gp_m3 := any(arena.takeFree(size, alignment)).(type) {
	case option.Some[int]:
		found := __gp_m3.Value

		offset = found
	case option.None[int]:

		offset = alignUp(arena.cursor, alignment)
		if offset > len(arena.storage) || size > len(arena.storage)-offset {
			return result.Err[Handle, Failure]{Err: CapacityExhausted{}}
		}
		arena.cursor = offset + size
	default:
		panic("goplus: impossible enum value in match")
	}
	id := arena.nextID
	arena.nextID++
	arena.allocations[id] = allocation{offset: offset, length: size, alive: true}
	arena.order = append(arena.order, id)
	arena.used += size
	if arena.used > arena.peak {
		arena.peak = arena.used
	}
	return result.Ok[Handle, Failure]{Value: Handle{
		id:         id,
		offset:     offset,
		length:     size,
		generation: arena.generation,
	}}
}

func (arena *Arena) Write(handle Handle, at int, source []byte) result.Result[Mutation, Failure] {
	arena.mu.Lock()
	defer arena.mu.Unlock()
	switch __gp_m4 := any(arena.resolve(handle)).(type) {
	case result.Err[allocation, Failure]:
		failure := __gp_m4.Err

		return result.Err[Mutation, Failure]{Err: failure}
	case result.Ok[allocation, Failure]:
		current := __gp_m4.Value

		if at < 0 || at > current.length || len(source) > current.length-at {
			return result.Err[Mutation, Failure]{Err: BoundsViolation{Operation: "write"}}
		}
		copy(arena.storage[current.offset+at:current.offset+at+len(source)], source)
		return result.Ok[Mutation, Failure]{Value: Applied{}}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (arena *Arena) Read(handle Handle, at int, destination []byte) result.Result[Mutation, Failure] {
	arena.mu.Lock()
	defer arena.mu.Unlock()
	switch __gp_m5 := any(arena.resolve(handle)).(type) {
	case result.Err[allocation, Failure]:
		failure := __gp_m5.Err

		return result.Err[Mutation, Failure]{Err: failure}
	case result.Ok[allocation, Failure]:
		current := __gp_m5.Value

		if at < 0 || at > current.length || len(destination) > current.length-at {
			return result.Err[Mutation, Failure]{Err: BoundsViolation{Operation: "read"}}
		}
		copy(destination, arena.storage[current.offset+at:current.offset+at+len(destination)])
		return result.Ok[Mutation, Failure]{Value: Applied{}}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (arena *Arena) Bytes(handle Handle) result.Result[[]byte, Failure] {
	arena.mu.Lock()
	defer arena.mu.Unlock()
	switch __gp_m6 := any(arena.resolve(handle)).(type) {
	case result.Err[allocation, Failure]:
		failure := __gp_m6.Err

		return result.Err[[]byte, Failure]{Err: failure}
	case result.Ok[allocation, Failure]:
		current := __gp_m6.Value

		out := make([]byte, current.length)
		copy(out, arena.storage[current.offset:current.offset+current.length])
		return result.Ok[[]byte, Failure]{Value: out}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (arena *Arena) Zero(handle Handle) result.Result[Mutation, Failure] {
	arena.mu.Lock()
	defer arena.mu.Unlock()
	switch __gp_m7 := any(arena.resolve(handle)).(type) {
	case result.Err[allocation, Failure]:
		failure := __gp_m7.Err

		return result.Err[Mutation, Failure]{Err: failure}
	case result.Ok[allocation, Failure]:
		current := __gp_m7.Value

		clear(arena.storage[current.offset : current.offset+current.length])
		return result.Ok[Mutation, Failure]{Value: Applied{}}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (arena *Arena) Delete(handle Handle) result.Result[Mutation, Failure] {
	arena.mu.Lock()
	defer arena.mu.Unlock()
	switch __gp_m8 := any(arena.resolve(handle)).(type) {
	case result.Err[allocation, Failure]:
		failure := __gp_m8.Err

		return result.Err[Mutation, Failure]{Err: failure}
	case result.Ok[allocation, Failure]:
		current := __gp_m8.Value

		arena.release(handle.id, current)
		arena.coalesce()
		return result.Ok[Mutation, Failure]{Value: Applied{}}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (arena *Arena) Checkpoint() result.Result[Checkpoint, Failure] {
	arena.mu.Lock()
	defer arena.mu.Unlock()
	if arena.closed {
		return result.Err[Checkpoint, Failure]{Err: ArenaClosed{}}
	}
	return result.Ok[Checkpoint, Failure]{Value: Checkpoint{
		arena:      arena.id,
		generation: arena.generation,
		order:      len(arena.order),
	}}
}

func (arena *Arena) Rollback(checkpoint Checkpoint) result.Result[Mutation, Failure] {
	arena.mu.Lock()
	defer arena.mu.Unlock()
	if arena.closed {
		return result.Err[Mutation, Failure]{Err: ArenaClosed{}}
	}
	if checkpoint.arena != arena.id ||
		checkpoint.generation != arena.generation ||
		checkpoint.order < 0 ||
		checkpoint.order > len(arena.order) {
		return result.Err[Mutation, Failure]{Err: InvalidCheckpoint{}}
	}
	for _, id := range arena.order[checkpoint.order:] {
		current, present := arena.allocations[id]
		currentOption := option.Of(current, present)
		switch __gp_m9 := any(currentOption).(type) {
		case option.Some[allocation]:
			current := __gp_m9.Value

			if current.alive {
				arena.release(id, current)
			}
		case option.None[allocation]:

		default:
			panic("goplus: impossible enum value in match")
		}
	}
	arena.order = arena.order[:checkpoint.order]
	arena.coalesce()
	return result.Ok[Mutation, Failure]{Value: Applied{}}
}

func (arena *Arena) Reset() result.Result[Mutation, Failure] {
	arena.mu.Lock()
	defer arena.mu.Unlock()
	if arena.closed {
		return result.Err[Mutation, Failure]{Err: ArenaClosed{}}
	}
	if zeroesReleased(arena.zero) {
		clear(arena.storage)
	}
	arena.cursor = 0
	arena.free = nil
	arena.allocations = map[uint64]allocation{}
	arena.order = nil
	arena.used = 0
	arena.generation++
	return result.Ok[Mutation, Failure]{Value: Applied{}}
}

func (arena *Arena) Stats() Stats {
	arena.mu.Lock()
	defer arena.mu.Unlock()
	return Stats{
		Capacity:    len(arena.storage),
		Used:        arena.used,
		Peak:        arena.peak,
		Allocations: arena.liveAllocations(),
		Generation:  arena.generation,
		Closed:      arena.closed,
	}
}

func (arena *Arena) Close() result.Result[Mutation, Failure] {
	arena.mu.Lock()
	defer arena.mu.Unlock()
	if arena.closed {
		return result.Ok[Mutation, Failure]{Value: Applied{}}
	}
	if zeroesReleased(arena.zero) {
		clear(arena.storage)
	}
	release := result.Of(struct{}{}, platformRelease(arena.storage))
	arena.storage = nil
	arena.free = nil
	arena.allocations = nil
	arena.order = nil
	arena.used = 0
	arena.closed = true
	arena.generation++
	switch __gp_m10 := any(release).(type) {
	case result.Ok[struct{}, error]:

		return result.Ok[Mutation, Failure]{Value: Applied{}}
	case result.Err[struct{}, error]:
		cause := __gp_m10.Err

		return result.Err[Mutation, Failure]{Err: PlatformFailure{Cause: cause}}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (arena *Arena) resolve(handle Handle) result.Result[allocation, Failure] {
	if arena.closed {
		return result.Err[allocation, Failure]{Err: ArenaClosed{}}
	}
	if handle.id == 0 || handle.generation != arena.generation {
		return result.Err[allocation, Failure]{Err: InvalidHandle{}}
	}
	current, present := arena.allocations[handle.id]
	currentOption := option.Of(current, present)
	switch __gp_m11 := any(currentOption).(type) {
	case option.None[allocation]:

		return result.Err[allocation, Failure]{Err: InvalidHandle{}}
	case option.Some[allocation]:
		current := __gp_m11.Value

		if !current.alive ||
			current.offset != handle.offset ||
			current.length != handle.length {
			return result.Err[allocation, Failure]{Err: InvalidHandle{}}
		}
		return result.Ok[allocation, Failure]{Value: current}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (arena *Arena) release(id uint64, current allocation) {
	if zeroesReleased(arena.zero) {
		clear(arena.storage[current.offset : current.offset+current.length])
	}
	current.alive = false
	arena.allocations[id] = current
	arena.free = append(arena.free, span{offset: current.offset, length: current.length})
	arena.used -= current.length
}

func (arena *Arena) takeFree(size int, alignment int) option.Option[int] {
	for index, candidate := range arena.free {
		offset := alignUp(candidate.offset, alignment)
		end := offset + size
		candidateEnd := candidate.offset + candidate.length
		if end > candidateEnd {
			continue
		}
		arena.free = append(arena.free[:index], arena.free[index+1:]...)
		if offset > candidate.offset {
			arena.free = append(arena.free, span{
				offset: candidate.offset,
				length: offset - candidate.offset,
			})
		}
		if end < candidateEnd {
			arena.free = append(arena.free, span{offset: end, length: candidateEnd - end})
		}
		return option.Some[int]{Value: offset}
	}
	return option.None[int]{}
}

func (arena *Arena) coalesce() {
	for leftIndex := 0; leftIndex < len(arena.free); leftIndex++ {
		for rightIndex := leftIndex + 1; rightIndex < len(arena.free); {
			left, right := arena.free[leftIndex], arena.free[rightIndex]
			if right.offset < left.offset {
				left, right = right, left
			}
			if left.offset+left.length == right.offset {
				arena.free[leftIndex] = span{
					offset: left.offset,
					length: left.length + right.length,
				}
				arena.free = append(arena.free[:rightIndex], arena.free[rightIndex+1:]...)
				continue
			}
			rightIndex++
		}
	}
}

func (arena *Arena) liveAllocations() int {
	count := 0
	for _, current := range arena.allocations {
		if current.alive {
			count++
		}
	}
	return count
}

func zeroesReleased(policy ZeroPolicy) bool {
	switch any(policy).(type) {
	case ZeroOnRelease:

		return true
	case PreserveOnRelease:

		return false
	default:
		panic("goplus: impossible enum value in match")
	}
}

func alignUp(value int, alignment int) int {
	return (value + alignment - 1) & ^(alignment - 1)
}
