// Code generated by goplus from memory_test.gp. DO NOT EDIT.
//goplus:v v0.28.0

package memory

import (
	"testing"
	"testing/quick"

	"goforge.dev/goplus/std/result"
)

func TestGenerationInvalidatesHandles(t *testing.T) {
	arena := requireArena(t)
	defer arena.Close()
	var handle Handle
	switch __gp_m0 := any(arena.Allocate(16, 8)).(type) {
	case result.Ok[Handle, Failure]:
		allocated := __gp_m0.Value

		handle = allocated
	case result.Err[Handle, Failure]:
		failure := __gp_m0.Err

		t.Fatal(failure)
	default:
		panic("goplus: impossible enum value in match")
	}
	switch __gp_m1 := any(arena.Reset()).(type) {
	case result.Ok[Mutation, Failure]:

	case result.Err[Mutation, Failure]:
		failure := __gp_m1.Err

		t.Fatal(failure)
	default:
		panic("goplus: impossible enum value in match")
	}
	switch __gp_m2 := any(arena.Bytes(handle)).(type) {
	case result.Ok[[]byte, Failure]:

		t.Fatal("expired handle was accepted")
	case result.Err[[]byte, Failure]:
		failure := __gp_m2.Err

		switch any(failure).(type) {
		case InvalidHandle:

		default:

			t.Fatalf("unexpected failure: %v", failure)
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func TestRollbackPreservesEarlierAllocations(t *testing.T) {
	arena := requireArena(t)
	defer arena.Close()
	first := requireAllocation(t, arena, 8, 8)
	var point Checkpoint
	switch __gp_m4 := any(arena.Checkpoint()).(type) {
	case result.Ok[Checkpoint, Failure]:
		checkpoint := __gp_m4.Value

		point = checkpoint
	case result.Err[Checkpoint, Failure]:
		failure := __gp_m4.Err

		t.Fatal(failure)
	default:
		panic("goplus: impossible enum value in match")
	}
	later := requireAllocation(t, arena, 8, 8)
	switch __gp_m5 := any(arena.Rollback(point)).(type) {
	case result.Ok[Mutation, Failure]:

	case result.Err[Mutation, Failure]:
		failure := __gp_m5.Err

		t.Fatal(failure)
	default:
		panic("goplus: impossible enum value in match")
	}
	switch __gp_m6 := any(arena.Bytes(first)).(type) {
	case result.Ok[[]byte, Failure]:

	case result.Err[[]byte, Failure]:
		failure := __gp_m6.Err

		t.Fatalf("earlier allocation expired: %v", failure)
	default:
		panic("goplus: impossible enum value in match")
	}
	switch __gp_m7 := any(arena.Bytes(later)).(type) {
	case result.Ok[[]byte, Failure]:

		t.Fatal("rolled-back handle survived")
	case result.Err[[]byte, Failure]:
		failure := __gp_m7.Err

		switch any(failure).(type) {
		case InvalidHandle:

		default:

			t.Fatalf("unexpected failure: %v", failure)
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func TestDeleteReuseNeverRevivesHandle(t *testing.T) {
	arena := requireArena(t)
	defer arena.Close()
	old := requireAllocation(t, arena, 64, 16)
	switch __gp_m9 := any(arena.Delete(old)).(type) {
	case result.Ok[Mutation, Failure]:

	case result.Err[Mutation, Failure]:
		failure := __gp_m9.Err

		t.Fatal(failure)
	default:
		panic("goplus: impossible enum value in match")
	}
	fresh := requireAllocation(t, arena, 64, 16)
	if old.offset != fresh.offset {
		t.Fatalf("allocation was not reused: old=%d fresh=%d", old.offset, fresh.offset)
	}
	switch __gp_m10 := any(arena.Bytes(old)).(type) {
	case result.Ok[[]byte, Failure]:

		t.Fatal("deleted handle revived")
	case result.Err[[]byte, Failure]:
		failure := __gp_m10.Err

		switch any(failure).(type) {
		case InvalidHandle:

		default:

			t.Fatalf("unexpected failure: %v", failure)
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func TestAlignedAllocationsProperty(t *testing.T) {
	property := func(rawSize uint16, exponent uint8) bool {
		size := int(rawSize%128) + 1
		alignment := 1 << (exponent % 6)
		switch __gp_m12 := any(New(Config{Capacity: 4096, Zero: ZeroOnRelease{}})).(type) {
		case result.Err[*Arena, Failure]:

			return false
		case result.Ok[*Arena, Failure]:
			arena := __gp_m12.Value

			defer arena.Close()
			switch __gp_m13 := any(arena.Allocate(size, alignment)).(type) {
			case result.Err[Handle, Failure]:

				return false
			case result.Ok[Handle, Failure]:
				handle := __gp_m13.Value

				return handle.offset%alignment == 0
			default:
				panic("goplus: impossible enum value in match")
			}
		default:
			panic("goplus: impossible enum value in match")
		}
	}
	switch __gp_m14 := any(result.Of(true, quick.Check(property, nil))).(type) {
	case result.Err[bool, error]:
		cause := __gp_m14.Err
		t.Fatal(cause)
	case result.Ok[bool, error]:

	default:
		panic("goplus: impossible enum value in match")
	}
}

func requireArena(t *testing.T) *Arena {
	switch __gp_m15 := any(New(Config{Capacity: 4096, Zero: ZeroOnRelease{}})).(type) {
	case result.Ok[*Arena, Failure]:
		arena := __gp_m15.Value

		return arena
	case result.Err[*Arena, Failure]:
		failure := __gp_m15.Err

		t.Fatal(failure)
		return nil
	default:
		panic("goplus: impossible enum value in match")
	}
}

func requireAllocation(t *testing.T, arena *Arena, size int, alignment int) Handle {
	switch __gp_m16 := any(arena.Allocate(size, alignment)).(type) {
	case result.Ok[Handle, Failure]:
		handle := __gp_m16.Value

		return handle
	case result.Err[Handle, Failure]:
		failure := __gp_m16.Err

		t.Fatal(failure)
		return Handle{}
	default:
		panic("goplus: impossible enum value in match")
	}
}
